//! Bulk operations for CalendarReligion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarReligionDto;
use crate::application::service::CalendarReligionService;
use crate::domain::entity::CalendarReligion;

/// Bulk operation handler for CalendarReligion entities.
///
/// Wraps `CalendarReligionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarReligionBulkService = GenericBulkService<CalendarReligion, CreateCalendarReligionDto, CalendarReligionService>;

// <<< CUSTOM
// END CUSTOM
