//! Bulk operations for CalendarEmployeeStatus entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarEmployeeStatusDto;
use crate::application::service::CalendarEmployeeStatusService;
use crate::domain::entity::CalendarEmployeeStatus;

/// Bulk operation handler for CalendarEmployeeStatus entities.
///
/// Wraps `CalendarEmployeeStatusService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarEmployeeStatusBulkService = GenericBulkService<CalendarEmployeeStatus, CreateCalendarEmployeeStatusDto, CalendarEmployeeStatusService>;

// <<< CUSTOM
// END CUSTOM
