//! Bulk operations for CalendarLevel entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarLevelDto;
use crate::application::service::CalendarLevelService;
use crate::domain::entity::CalendarLevel;

/// Bulk operation handler for CalendarLevel entities.
///
/// Wraps `CalendarLevelService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarLevelBulkService = GenericBulkService<CalendarLevel, CreateCalendarLevelDto, CalendarLevelService>;

// <<< CUSTOM
// END CUSTOM
