//! Bulk operations for CalendarEmployee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarEmployeeDto;
use crate::application::service::CalendarEmployeeService;
use crate::domain::entity::CalendarEmployee;

/// Bulk operation handler for CalendarEmployee entities.
///
/// Wraps `CalendarEmployeeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarEmployeeBulkService = GenericBulkService<CalendarEmployee, CreateCalendarEmployeeDto, CalendarEmployeeService>;

// <<< CUSTOM
// END CUSTOM
