//! Bulk operations for CalendarDepartment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarDepartmentDto;
use crate::application::service::CalendarDepartmentService;
use crate::domain::entity::CalendarDepartment;

/// Bulk operation handler for CalendarDepartment entities.
///
/// Wraps `CalendarDepartmentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarDepartmentBulkService = GenericBulkService<CalendarDepartment, CreateCalendarDepartmentDto, CalendarDepartmentService>;

// <<< CUSTOM
// END CUSTOM
