//! Bulk operations for CalendarPosition entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCalendarPositionDto;
use crate::application::service::CalendarPositionService;
use crate::domain::entity::CalendarPosition;

/// Bulk operation handler for CalendarPosition entities.
///
/// Wraps `CalendarPositionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CalendarPositionBulkService = GenericBulkService<CalendarPosition, CreateCalendarPositionDto, CalendarPositionService>;

// <<< CUSTOM
// END CUSTOM
