//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod calendar_bulk;
pub mod calendar_branch_bulk;
pub mod calendar_department_bulk;
pub mod calendar_employee_bulk;
pub mod calendar_employee_status_bulk;
pub mod calendar_level_bulk;
pub mod calendar_position_bulk;
pub mod calendar_religion_bulk;

pub use calendar_bulk::CalendarBulkService;
pub use calendar_branch_bulk::CalendarBranchBulkService;
pub use calendar_department_bulk::CalendarDepartmentBulkService;
pub use calendar_employee_bulk::CalendarEmployeeBulkService;
pub use calendar_employee_status_bulk::CalendarEmployeeStatusBulkService;
pub use calendar_level_bulk::CalendarLevelBulkService;
pub use calendar_position_bulk::CalendarPositionBulkService;
pub use calendar_religion_bulk::CalendarReligionBulkService;

// <<< CUSTOM
// END CUSTOM
