//! CalendarEventAttendee DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarEventAttendee;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EventAttendeeState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarEventAttendee
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarEventAttendeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    pub state: EventAttendeeState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "access_token")]
    pub access_token: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarEventAttendee
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarEventAttendeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    pub state: EventAttendeeState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "access_token")]
    pub access_token: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarEventAttendee
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarEventAttendeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<EventAttendeeState>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "access_token")]
    pub access_token: Option<Uuid>,
}

impl PatchCalendarEventAttendeeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.event_id.is_some() || self.user_id.is_some() || self.state.is_some() || self.access_token.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarEventAttendee entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventAttendeeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub state: EventAttendeeState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub access_token: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarEventAttendee entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventAttendeeListResponseDto {
    /// List of items
    pub items: Vec<CalendarEventAttendeeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarEventAttendeeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarEventAttendeeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventAttendeeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub event_id: Uuid,
    pub user_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarEventAttendee> for CalendarEventAttendeeResponseDto {
    fn from(entity: CalendarEventAttendee) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            event_id: entity.event_id,
            user_id: entity.user_id,
            state: entity.state,
            access_token: entity.access_token,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarEventAttendee> for CalendarEventAttendeeSummaryDto {
    fn from(entity: CalendarEventAttendee) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            event_id: entity.event_id,
            user_id: entity.user_id,
            created_at,
        }
    }
}

impl From<CreateCalendarEventAttendeeDto> for CalendarEventAttendee {
    fn from(dto: CreateCalendarEventAttendeeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            event_id: dto.event_id,
            user_id: dto.user_id,
            state: dto.state,
            access_token: dto.access_token,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarEventAttendee> for CalendarEventAttendeeResponseDto {
    fn from(entity: &CalendarEventAttendee) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            event_id: entity.event_id.clone(),
            user_id: entity.user_id.clone(),
            state: entity.state.clone(),
            access_token: entity.access_token.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarEventAttendeeDto> for CalendarEventAttendee {
    fn from_create_dto(dto: CreateCalendarEventAttendeeDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarEventAttendee::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarEventAttendeeDto> for CalendarEventAttendee {
    fn apply_update(mut self, dto: UpdateCalendarEventAttendeeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.event_id = dto.event_id;
        self.user_id = dto.user_id;
        self.state = dto.state;
        self.access_token = dto.access_token;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarEventAttendee here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
