//! CalendarDepartment DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarDepartment;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarDepartment
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "calendar_id")]
    pub calendar_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "department_id")]
    pub department_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarDepartment
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "calendar_id")]
    pub calendar_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "department_id")]
    pub department_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarDepartment
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "calendar_id")]
    pub calendar_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
}

impl PatchCalendarDepartmentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.calendar_id.is_some() || self.department_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarDepartment entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarDepartmentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub calendar_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub department_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarDepartment entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarDepartmentListResponseDto {
    /// List of items
    pub items: Vec<CalendarDepartmentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarDepartmentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarDepartmentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarDepartmentSummaryDto {
    pub id: Uuid,
    pub calendar_id: Uuid,
    pub department_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarDepartment> for CalendarDepartmentResponseDto {
    fn from(entity: CalendarDepartment) -> Self {
        Self {
            id: entity.id,
            calendar_id: entity.calendar_id,
            department_id: entity.department_id,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarDepartment> for CalendarDepartmentSummaryDto {
    fn from(entity: CalendarDepartment) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            calendar_id: entity.calendar_id,
            department_id: entity.department_id,
            created_at,
        }
    }
}

impl From<CreateCalendarDepartmentDto> for CalendarDepartment {
    fn from(dto: CreateCalendarDepartmentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            calendar_id: dto.calendar_id,
            department_id: dto.department_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarDepartment> for CalendarDepartmentResponseDto {
    fn from(entity: &CalendarDepartment) -> Self {
        Self {
            id: entity.id.clone(),
            calendar_id: entity.calendar_id.clone(),
            department_id: entity.department_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarDepartmentDto> for CalendarDepartment {
    fn from_create_dto(dto: CreateCalendarDepartmentDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarDepartment::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarDepartmentDto> for CalendarDepartment {
    fn apply_update(mut self, dto: UpdateCalendarDepartmentDto) -> backbone_core::ServiceResult<Self> {
        self.calendar_id = dto.calendar_id;
        self.department_id = dto.department_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarDepartment here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
