//! CalendarEvent DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarEvent;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EventPrivacy;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarEvent
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarEventDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "series_id")]
    pub series_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "start_at")]
    pub start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "stop_at")]
    pub stop_at: DateTime<Utc>,
    pub privacy: EventPrivacy,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "organizer_user_id")]
    pub organizer_user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarEvent
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarEventDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "series_id")]
    pub series_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "start_at")]
    pub start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "stop_at")]
    pub stop_at: DateTime<Utc>,
    pub privacy: EventPrivacy,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "organizer_user_id")]
    pub organizer_user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarEvent
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarEventDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "series_id")]
    pub series_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_at")]
    pub start_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "stop_at")]
    pub stop_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy: Option<EventPrivacy>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "organizer_user_id")]
    pub organizer_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

impl PatchCalendarEventDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.series_id.is_some() || self.title.is_some() || self.description.is_some() || self.start_at.is_some() || self.stop_at.is_some() || self.privacy.is_some() || self.organizer_user_id.is_some() || self.location.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarEvent entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub series_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub stop_at: DateTime<Utc>,
    pub privacy: EventPrivacy,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub organizer_user_id: Uuid,
    pub location: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarEvent entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventListResponseDto {
    /// List of items
    pub items: Vec<CalendarEventResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarEventListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarEventResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub series_id: Option<Uuid>,
    pub title: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarEvent> for CalendarEventResponseDto {
    fn from(entity: CalendarEvent) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            series_id: entity.series_id,
            title: entity.title,
            description: entity.description,
            start_at: entity.start_at,
            stop_at: entity.stop_at,
            privacy: entity.privacy,
            organizer_user_id: entity.organizer_user_id,
            location: entity.location,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarEvent> for CalendarEventSummaryDto {
    fn from(entity: CalendarEvent) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            series_id: entity.series_id,
            title: entity.title,
            created_at,
        }
    }
}

impl From<CreateCalendarEventDto> for CalendarEvent {
    fn from(dto: CreateCalendarEventDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            series_id: dto.series_id,
            title: dto.title,
            description: dto.description,
            start_at: dto.start_at,
            stop_at: dto.stop_at,
            privacy: dto.privacy,
            organizer_user_id: dto.organizer_user_id,
            location: dto.location,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarEvent> for CalendarEventResponseDto {
    fn from(entity: &CalendarEvent) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            series_id: entity.series_id.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            start_at: entity.start_at.clone(),
            stop_at: entity.stop_at.clone(),
            privacy: entity.privacy.clone(),
            organizer_user_id: entity.organizer_user_id.clone(),
            location: entity.location.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarEventDto> for CalendarEvent {
    fn from_create_dto(dto: CreateCalendarEventDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarEvent::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarEventDto> for CalendarEvent {
    fn apply_update(mut self, dto: UpdateCalendarEventDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.series_id = dto.series_id;
        self.title = dto.title;
        self.description = dto.description;
        self.start_at = dto.start_at;
        self.stop_at = dto.stop_at;
        self.privacy = dto.privacy;
        self.organizer_user_id = dto.organizer_user_id;
        self.location = dto.location;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarEvent here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
