//! CalendarEmployeeStatus DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarEmployeeStatus;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EmploymentStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarEmployeeStatus
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarEmployeeStatusDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "calendar_id")]
    pub calendar_id: Uuid,
    #[serde(alias = "employment_status")]
    pub employment_status: EmploymentStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarEmployeeStatus
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarEmployeeStatusDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "calendar_id")]
    pub calendar_id: Uuid,
    #[serde(alias = "employment_status")]
    pub employment_status: EmploymentStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarEmployeeStatus
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarEmployeeStatusDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "calendar_id")]
    pub calendar_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_status")]
    pub employment_status: Option<EmploymentStatus>,
}

impl PatchCalendarEmployeeStatusDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.calendar_id.is_some() || self.employment_status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarEmployeeStatus entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEmployeeStatusResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub calendar_id: Uuid,
    pub employment_status: EmploymentStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarEmployeeStatus entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEmployeeStatusListResponseDto {
    /// List of items
    pub items: Vec<CalendarEmployeeStatusResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarEmployeeStatusListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarEmployeeStatusResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEmployeeStatusSummaryDto {
    pub id: Uuid,
    pub calendar_id: Uuid,
    pub employment_status: EmploymentStatus,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarEmployeeStatus> for CalendarEmployeeStatusResponseDto {
    fn from(entity: CalendarEmployeeStatus) -> Self {
        Self {
            id: entity.id,
            calendar_id: entity.calendar_id,
            employment_status: entity.employment_status,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarEmployeeStatus> for CalendarEmployeeStatusSummaryDto {
    fn from(entity: CalendarEmployeeStatus) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            calendar_id: entity.calendar_id,
            employment_status: entity.employment_status,
            created_at,
        }
    }
}

impl From<CreateCalendarEmployeeStatusDto> for CalendarEmployeeStatus {
    fn from(dto: CreateCalendarEmployeeStatusDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            calendar_id: dto.calendar_id,
            employment_status: dto.employment_status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarEmployeeStatus> for CalendarEmployeeStatusResponseDto {
    fn from(entity: &CalendarEmployeeStatus) -> Self {
        Self {
            id: entity.id.clone(),
            calendar_id: entity.calendar_id.clone(),
            employment_status: entity.employment_status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarEmployeeStatusDto> for CalendarEmployeeStatus {
    fn from_create_dto(dto: CreateCalendarEmployeeStatusDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarEmployeeStatus::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarEmployeeStatusDto> for CalendarEmployeeStatus {
    fn apply_update(mut self, dto: UpdateCalendarEmployeeStatusDto) -> backbone_core::ServiceResult<Self> {
        self.calendar_id = dto.calendar_id;
        self.employment_status = dto.employment_status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarEmployeeStatus here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
