//! CalendarEventSeries DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarEventSeries;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EventRecurrenceFreq;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarEventSeries
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarEventSeriesDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub freq: EventRecurrenceFreq,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub interval: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "by_weekday")]
    pub by_weekday: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "by_monthday")]
    pub by_monthday: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub until: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "base_event_id")]
    pub base_event_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarEventSeries
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarEventSeriesDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub freq: EventRecurrenceFreq,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub interval: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "by_weekday")]
    pub by_weekday: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "by_monthday")]
    pub by_monthday: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub until: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "base_event_id")]
    pub base_event_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarEventSeries
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarEventSeriesDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub freq: Option<EventRecurrenceFreq>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interval: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "by_weekday")]
    pub by_weekday: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "by_monthday")]
    pub by_monthday: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub until: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "base_event_id")]
    pub base_event_id: Option<Uuid>,
}

impl PatchCalendarEventSeriesDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.freq.is_some() || self.interval.is_some() || self.by_weekday.is_some() || self.by_monthday.is_some() || self.until.is_some() || self.count.is_some() || self.base_event_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarEventSeries entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventSeriesResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub name: Option<String>,
    pub freq: EventRecurrenceFreq,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub interval: i32,
    pub by_weekday: Option<String>,
    pub by_monthday: Option<String>,
    pub until: Option<NaiveDate>,
    pub count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub base_event_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarEventSeries entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventSeriesListResponseDto {
    /// List of items
    pub items: Vec<CalendarEventSeriesResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarEventSeriesListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarEventSeriesResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventSeriesSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: Option<String>,
    pub freq: EventRecurrenceFreq,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarEventSeries> for CalendarEventSeriesResponseDto {
    fn from(entity: CalendarEventSeries) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            freq: entity.freq,
            interval: entity.interval,
            by_weekday: entity.by_weekday,
            by_monthday: entity.by_monthday,
            until: entity.until,
            count: entity.count,
            base_event_id: entity.base_event_id,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarEventSeries> for CalendarEventSeriesSummaryDto {
    fn from(entity: CalendarEventSeries) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            freq: entity.freq,
            created_at,
        }
    }
}

impl From<CreateCalendarEventSeriesDto> for CalendarEventSeries {
    fn from(dto: CreateCalendarEventSeriesDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            freq: dto.freq,
            interval: dto.interval,
            by_weekday: dto.by_weekday,
            by_monthday: dto.by_monthday,
            until: dto.until,
            count: dto.count,
            base_event_id: dto.base_event_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarEventSeries> for CalendarEventSeriesResponseDto {
    fn from(entity: &CalendarEventSeries) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            freq: entity.freq.clone(),
            interval: entity.interval.clone(),
            by_weekday: entity.by_weekday.clone(),
            by_monthday: entity.by_monthday.clone(),
            until: entity.until.clone(),
            count: entity.count.clone(),
            base_event_id: entity.base_event_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarEventSeriesDto> for CalendarEventSeries {
    fn from_create_dto(dto: CreateCalendarEventSeriesDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarEventSeries::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarEventSeriesDto> for CalendarEventSeries {
    fn apply_update(mut self, dto: UpdateCalendarEventSeriesDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.freq = dto.freq;
        self.interval = dto.interval;
        self.by_weekday = dto.by_weekday;
        self.by_monthday = dto.by_monthday;
        self.until = dto.until;
        self.count = dto.count;
        self.base_event_id = dto.base_event_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarEventSeries here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
