//! CalendarEventException DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CalendarEventException;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EventExceptionKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CalendarEventException
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCalendarEventExceptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "series_id")]
    pub series_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "slot_start_at")]
    pub slot_start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "slot_stop_at")]
    pub slot_stop_at: DateTime<Utc>,
    pub kind: EventExceptionKind,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CalendarEventException
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCalendarEventExceptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "series_id")]
    pub series_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "slot_start_at")]
    pub slot_start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "slot_stop_at")]
    pub slot_stop_at: DateTime<Utc>,
    pub kind: EventExceptionKind,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CalendarEventException
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCalendarEventExceptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "series_id")]
    pub series_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "slot_start_at")]
    pub slot_start_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "slot_stop_at")]
    pub slot_stop_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<EventExceptionKind>,
}

impl PatchCalendarEventExceptionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.series_id.is_some() || self.event_id.is_some() || self.slot_start_at.is_some() || self.slot_stop_at.is_some() || self.kind.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CalendarEventException entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventExceptionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub series_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub slot_start_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub slot_stop_at: DateTime<Utc>,
    pub kind: EventExceptionKind,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CalendarEventException entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventExceptionListResponseDto {
    /// List of items
    pub items: Vec<CalendarEventExceptionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CalendarEventExceptionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CalendarEventExceptionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CalendarEventExceptionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub series_id: Uuid,
    pub event_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CalendarEventException> for CalendarEventExceptionResponseDto {
    fn from(entity: CalendarEventException) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            series_id: entity.series_id,
            event_id: entity.event_id,
            slot_start_at: entity.slot_start_at,
            slot_stop_at: entity.slot_stop_at,
            kind: entity.kind,
            metadata: entity.metadata,
        }
    }
}

impl From<CalendarEventException> for CalendarEventExceptionSummaryDto {
    fn from(entity: CalendarEventException) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            series_id: entity.series_id,
            event_id: entity.event_id,
            created_at,
        }
    }
}

impl From<CreateCalendarEventExceptionDto> for CalendarEventException {
    fn from(dto: CreateCalendarEventExceptionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            series_id: dto.series_id,
            event_id: dto.event_id,
            slot_start_at: dto.slot_start_at,
            slot_stop_at: dto.slot_stop_at,
            kind: dto.kind,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CalendarEventException> for CalendarEventExceptionResponseDto {
    fn from(entity: &CalendarEventException) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            series_id: entity.series_id.clone(),
            event_id: entity.event_id.clone(),
            slot_start_at: entity.slot_start_at.clone(),
            slot_stop_at: entity.slot_stop_at.clone(),
            kind: entity.kind.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCalendarEventExceptionDto> for CalendarEventException {
    fn from_create_dto(dto: CreateCalendarEventExceptionDto) -> backbone_core::ServiceResult<Self> {
        Ok(CalendarEventException::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCalendarEventExceptionDto> for CalendarEventException {
    fn apply_update(mut self, dto: UpdateCalendarEventExceptionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.series_id = dto.series_id;
        self.event_id = dto.event_id;
        self.slot_start_at = dto.slot_start_at;
        self.slot_stop_at = dto.slot_stop_at;
        self.kind = dto.kind;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CalendarEventException here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
