//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod calendar_dto;
pub mod calendar_branch_dto;
pub mod calendar_department_dto;
pub mod calendar_employee_dto;
pub mod calendar_employee_status_dto;
pub mod calendar_event_dto;
pub mod calendar_event_attendee_dto;
pub mod calendar_event_exception_dto;
pub mod calendar_event_series_dto;
pub mod calendar_level_dto;
pub mod calendar_position_dto;
pub mod calendar_religion_dto;

// Re-exports
pub use calendar_dto::{
    CreateCalendarDto,
    UpdateCalendarDto,
    PatchCalendarDto,
    CalendarResponseDto,
    CalendarListResponseDto,
    CalendarSummaryDto,
};
pub use calendar_branch_dto::{
    CreateCalendarBranchDto,
    UpdateCalendarBranchDto,
    PatchCalendarBranchDto,
    CalendarBranchResponseDto,
    CalendarBranchListResponseDto,
    CalendarBranchSummaryDto,
};
pub use calendar_department_dto::{
    CreateCalendarDepartmentDto,
    UpdateCalendarDepartmentDto,
    PatchCalendarDepartmentDto,
    CalendarDepartmentResponseDto,
    CalendarDepartmentListResponseDto,
    CalendarDepartmentSummaryDto,
};
pub use calendar_employee_dto::{
    CreateCalendarEmployeeDto,
    UpdateCalendarEmployeeDto,
    PatchCalendarEmployeeDto,
    CalendarEmployeeResponseDto,
    CalendarEmployeeListResponseDto,
    CalendarEmployeeSummaryDto,
};
pub use calendar_employee_status_dto::{
    CreateCalendarEmployeeStatusDto,
    UpdateCalendarEmployeeStatusDto,
    PatchCalendarEmployeeStatusDto,
    CalendarEmployeeStatusResponseDto,
    CalendarEmployeeStatusListResponseDto,
    CalendarEmployeeStatusSummaryDto,
};
pub use calendar_event_dto::{
    CreateCalendarEventDto,
    UpdateCalendarEventDto,
    PatchCalendarEventDto,
    CalendarEventResponseDto,
    CalendarEventListResponseDto,
    CalendarEventSummaryDto,
};
pub use calendar_event_attendee_dto::{
    CreateCalendarEventAttendeeDto,
    UpdateCalendarEventAttendeeDto,
    PatchCalendarEventAttendeeDto,
    CalendarEventAttendeeResponseDto,
    CalendarEventAttendeeListResponseDto,
    CalendarEventAttendeeSummaryDto,
};
pub use calendar_event_exception_dto::{
    CreateCalendarEventExceptionDto,
    UpdateCalendarEventExceptionDto,
    PatchCalendarEventExceptionDto,
    CalendarEventExceptionResponseDto,
    CalendarEventExceptionListResponseDto,
    CalendarEventExceptionSummaryDto,
};
pub use calendar_event_series_dto::{
    CreateCalendarEventSeriesDto,
    UpdateCalendarEventSeriesDto,
    PatchCalendarEventSeriesDto,
    CalendarEventSeriesResponseDto,
    CalendarEventSeriesListResponseDto,
    CalendarEventSeriesSummaryDto,
};
pub use calendar_level_dto::{
    CreateCalendarLevelDto,
    UpdateCalendarLevelDto,
    PatchCalendarLevelDto,
    CalendarLevelResponseDto,
    CalendarLevelListResponseDto,
    CalendarLevelSummaryDto,
};
pub use calendar_position_dto::{
    CreateCalendarPositionDto,
    UpdateCalendarPositionDto,
    PatchCalendarPositionDto,
    CalendarPositionResponseDto,
    CalendarPositionListResponseDto,
    CalendarPositionSummaryDto,
};
pub use calendar_religion_dto::{
    CreateCalendarReligionDto,
    UpdateCalendarReligionDto,
    PatchCalendarReligionDto,
    CalendarReligionResponseDto,
    CalendarReligionListResponseDto,
    CalendarReligionSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
