//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod calendar_specification;
pub mod calendar_branch_specification;
pub mod calendar_department_specification;
pub mod calendar_employee_specification;
pub mod calendar_employee_status_specification;
pub mod calendar_level_specification;
pub mod calendar_position_specification;
pub mod calendar_religion_specification;

// <<< CUSTOM
// END CUSTOM
