//! Domain policy for CalendarBranch aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::CalendarBranch;

/// Domain policy for CalendarBranch — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<CalendarBranch>` in the `// <<< CUSTOM` zone.
pub type CalendarBranchDomainPolicy = PermitAllPolicy<CalendarBranch>;

// <<< CUSTOM
// END CUSTOM
