//! Domain policy for CalendarEmployee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::CalendarEmployee;

/// Domain policy for CalendarEmployee — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<CalendarEmployee>` in the `// <<< CUSTOM` zone.
pub type CalendarEmployeeDomainPolicy = PermitAllPolicy<CalendarEmployee>;

// <<< CUSTOM
// END CUSTOM
