//! Domain policy for Calendar aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Calendar;

/// Domain policy for Calendar — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Calendar>` in the `// <<< CUSTOM` zone.
pub type CalendarDomainPolicy = PermitAllPolicy<Calendar>;

// <<< CUSTOM
// END CUSTOM
