//! Domain policy for CalendarEmployeeStatus aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::CalendarEmployeeStatus;

/// Domain policy for CalendarEmployeeStatus — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<CalendarEmployeeStatus>` in the `// <<< CUSTOM` zone.
pub type CalendarEmployeeStatusDomainPolicy = PermitAllPolicy<CalendarEmployeeStatus>;

// <<< CUSTOM
// END CUSTOM
