//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod calendar_domain_policy;
pub mod calendar_branch_domain_policy;
pub mod calendar_department_domain_policy;
pub mod calendar_employee_domain_policy;
pub mod calendar_employee_status_domain_policy;
pub mod calendar_level_domain_policy;
pub mod calendar_position_domain_policy;
pub mod calendar_religion_domain_policy;

pub use calendar_domain_policy::CalendarDomainPolicy;
pub use calendar_branch_domain_policy::CalendarBranchDomainPolicy;
pub use calendar_department_domain_policy::CalendarDepartmentDomainPolicy;
pub use calendar_employee_domain_policy::CalendarEmployeeDomainPolicy;
pub use calendar_employee_status_domain_policy::CalendarEmployeeStatusDomainPolicy;
pub use calendar_level_domain_policy::CalendarLevelDomainPolicy;
pub use calendar_position_domain_policy::CalendarPositionDomainPolicy;
pub use calendar_religion_domain_policy::CalendarReligionDomainPolicy;

// <<< CUSTOM
// END CUSTOM
