//! Application service for Calendar entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarDto, UpdateCalendarDto};
use crate::domain::entity::Calendar;
use crate::infrastructure::persistence::CalendarRepository;

/// Application service for Calendar entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarServiceCustom {
///     inner: Arc<CalendarService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarService = GenericCrudService<
    Calendar,
    CreateCalendarDto,
    UpdateCalendarDto,
    CalendarRepository,
>;

// <<< CUSTOM
// END CUSTOM
