//! Application service for CalendarPosition entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_position_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarPositionDto, UpdateCalendarPositionDto};
use crate::domain::entity::CalendarPosition;
use crate::infrastructure::persistence::CalendarPositionRepository;

/// Application service for CalendarPosition entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_position_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarPositionServiceCustom {
///     inner: Arc<CalendarPositionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarPositionService = GenericCrudService<
    CalendarPosition,
    CreateCalendarPositionDto,
    UpdateCalendarPositionDto,
    CalendarPositionRepository,
>;

// <<< CUSTOM
// END CUSTOM
