//! Application service for CalendarEvent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_event_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarEventDto, UpdateCalendarEventDto};
use crate::domain::entity::CalendarEvent;
use crate::infrastructure::persistence::CalendarEventRepository;

/// Application service for CalendarEvent entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_event_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarEventServiceCustom {
///     inner: Arc<CalendarEventService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarEventService = GenericCrudService<
    CalendarEvent,
    CreateCalendarEventDto,
    UpdateCalendarEventDto,
    CalendarEventRepository,
>;

// <<< CUSTOM
// END CUSTOM
