//! Application service for CalendarEmployeeStatus entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_employee_status_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarEmployeeStatusDto, UpdateCalendarEmployeeStatusDto};
use crate::domain::entity::CalendarEmployeeStatus;
use crate::infrastructure::persistence::CalendarEmployeeStatusRepository;

/// Application service for CalendarEmployeeStatus entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_employee_status_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarEmployeeStatusServiceCustom {
///     inner: Arc<CalendarEmployeeStatusService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarEmployeeStatusService = GenericCrudService<
    CalendarEmployeeStatus,
    CreateCalendarEmployeeStatusDto,
    UpdateCalendarEmployeeStatusDto,
    CalendarEmployeeStatusRepository,
>;

// <<< CUSTOM
// END CUSTOM
