//! Application service for CalendarReligion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_religion_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarReligionDto, UpdateCalendarReligionDto};
use crate::domain::entity::CalendarReligion;
use crate::infrastructure::persistence::CalendarReligionRepository;

/// Application service for CalendarReligion entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_religion_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarReligionServiceCustom {
///     inner: Arc<CalendarReligionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarReligionService = GenericCrudService<
    CalendarReligion,
    CreateCalendarReligionDto,
    UpdateCalendarReligionDto,
    CalendarReligionRepository,
>;

// <<< CUSTOM
// END CUSTOM
