//! Application service for CalendarBranch entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_branch_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarBranchDto, UpdateCalendarBranchDto};
use crate::domain::entity::CalendarBranch;
use crate::infrastructure::persistence::CalendarBranchRepository;

/// Application service for CalendarBranch entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_branch_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarBranchServiceCustom {
///     inner: Arc<CalendarBranchService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarBranchService = GenericCrudService<
    CalendarBranch,
    CreateCalendarBranchDto,
    UpdateCalendarBranchDto,
    CalendarBranchRepository,
>;

// <<< CUSTOM
// END CUSTOM
