//! Application service for CalendarEventAttendee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_event_attendee_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarEventAttendeeDto, UpdateCalendarEventAttendeeDto};
use crate::domain::entity::CalendarEventAttendee;
use crate::infrastructure::persistence::CalendarEventAttendeeRepository;

/// Application service for CalendarEventAttendee entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_event_attendee_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarEventAttendeeServiceCustom {
///     inner: Arc<CalendarEventAttendeeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarEventAttendeeService = GenericCrudService<
    CalendarEventAttendee,
    CreateCalendarEventAttendeeDto,
    UpdateCalendarEventAttendeeDto,
    CalendarEventAttendeeRepository,
>;

// <<< CUSTOM
// END CUSTOM
