//! Application service for CalendarEventException entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_event_exception_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarEventExceptionDto, UpdateCalendarEventExceptionDto};
use crate::domain::entity::CalendarEventException;
use crate::infrastructure::persistence::CalendarEventExceptionRepository;

/// Application service for CalendarEventException entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_event_exception_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarEventExceptionServiceCustom {
///     inner: Arc<CalendarEventExceptionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarEventExceptionService = GenericCrudService<
    CalendarEventException,
    CreateCalendarEventExceptionDto,
    UpdateCalendarEventExceptionDto,
    CalendarEventExceptionRepository,
>;

// <<< CUSTOM
// END CUSTOM
