//! Application service for CalendarEventSeries entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_event_series_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarEventSeriesDto, UpdateCalendarEventSeriesDto};
use crate::domain::entity::CalendarEventSeries;
use crate::infrastructure::persistence::CalendarEventSeriesRepository;

/// Application service for CalendarEventSeries entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_event_series_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarEventSeriesServiceCustom {
///     inner: Arc<CalendarEventSeriesService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarEventSeriesService = GenericCrudService<
    CalendarEventSeries,
    CreateCalendarEventSeriesDto,
    UpdateCalendarEventSeriesDto,
    CalendarEventSeriesRepository,
>;

// <<< CUSTOM
// END CUSTOM
