//! Application service for CalendarLevel entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_level_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarLevelDto, UpdateCalendarLevelDto};
use crate::domain::entity::CalendarLevel;
use crate::infrastructure::persistence::CalendarLevelRepository;

/// Application service for CalendarLevel entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_level_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarLevelServiceCustom {
///     inner: Arc<CalendarLevelService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarLevelService = GenericCrudService<
    CalendarLevel,
    CreateCalendarLevelDto,
    UpdateCalendarLevelDto,
    CalendarLevelRepository,
>;

// <<< CUSTOM
// END CUSTOM
