//! Application service for CalendarDepartment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `calendar_department_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCalendarDepartmentDto, UpdateCalendarDepartmentDto};
use crate::domain::entity::CalendarDepartment;
use crate::infrastructure::persistence::CalendarDepartmentRepository;

/// Application service for CalendarDepartment entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `calendar_department_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CalendarDepartmentServiceCustom {
///     inner: Arc<CalendarDepartmentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CalendarDepartmentService = GenericCrudService<
    CalendarDepartment,
    CreateCalendarDepartmentDto,
    UpdateCalendarDepartmentDto,
    CalendarDepartmentRepository,
>;

// <<< CUSTOM
// END CUSTOM
