//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod calendar_service;
pub mod calendar_branch_service;
pub mod calendar_department_service;
pub mod calendar_employee_service;
pub mod calendar_employee_status_service;
pub mod calendar_level_service;
pub mod calendar_position_service;
pub mod calendar_religion_service;

// <<< CUSTOM
pub mod calendar_query_service;
// END CUSTOM

pub use calendar_service::CalendarService;
pub use calendar_branch_service::CalendarBranchService;
pub use calendar_department_service::CalendarDepartmentService;
pub use calendar_employee_service::CalendarEmployeeService;
pub use calendar_employee_status_service::CalendarEmployeeStatusService;
pub use calendar_level_service::CalendarLevelService;
pub use calendar_position_service::CalendarPositionService;
pub use calendar_religion_service::CalendarReligionService;
// <<< CUSTOM
// END CUSTOM
