-- CalendarEventException Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the calendar.event_exceptions table.
-- Customize this file to add your initial data.

-- INSERT INTO calendar.event_exceptions (
--     id,
--     company_id,
--     series_id,
--     event_id,
--     slot_start_at,
--     slot_stop_at,
--     kind,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO calendar.event_exceptions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

