-- CalendarEventAttendee Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the calendar.event_attendees table.
-- Customize this file to add your initial data.

-- INSERT INTO calendar.event_attendees (
--     id,
--     company_id,
--     event_id,
--     user_id,
--     state,
--     access_token,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO calendar.event_attendees (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

