-- CalendarEvent Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the calendar.events table.
-- Customize this file to add your initial data.

-- INSERT INTO calendar.events (
--     id,
--     company_id,
--     series_id,
--     title,
--     description,
--     start_at,
--     stop_at,
--     privacy,
--     organizer_user_id,
--     location,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO calendar.events (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

