-- CalendarEmployeeStatus Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the calendar.calendar_employee_statuses table.
-- Customize this file to add your initial data.

-- INSERT INTO calendar.calendar_employee_statuses (
--     id,
--     calendar_id,
--     employment_status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO calendar.calendar_employee_statuses (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

