-- Migration: Create calendar_employee_statuses table
-- Generated by metaphor-schema

-- Create employment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_status') THEN
        CREATE TYPE employment_status AS ENUM ('permanent', 'contract', 'probation', 'associate');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS calendar;

CREATE TABLE IF NOT EXISTS calendar.calendar_employee_statuses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    calendar_id UUID NOT NULL,
    employment_status employment_status NOT NULL DEFAULT 'permanent',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_employee_statuses_calendar_id ON calendar.calendar_employee_statuses (calendar_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_calendar_employee_statuses_metadata_gin ON calendar.calendar_employee_statuses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_calendar_employee_statuses_metadata_deleted_at ON calendar.calendar_employee_statuses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_calendar_employee_statuses_metadata_created_at ON calendar.calendar_employee_statuses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_calendar_employee_statuses_metadata_updated_at ON calendar.calendar_employee_statuses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION calendar.calendar_employee_statuses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_employee_statuses_insert_audit ON calendar.calendar_employee_statuses;
CREATE TRIGGER calendar_employee_statuses_insert_audit BEFORE INSERT ON calendar.calendar_employee_statuses
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employee_statuses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_employee_statuses_update_audit ON calendar.calendar_employee_statuses;
CREATE TRIGGER calendar_employee_statuses_update_audit BEFORE UPDATE ON calendar.calendar_employee_statuses
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employee_statuses_audit_timestamp();
