-- Migration: Create calendar_levels table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS calendar;

CREATE TABLE IF NOT EXISTS calendar.calendar_levels (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    calendar_id UUID NOT NULL,
    level_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_levels_calendar_id ON calendar.calendar_levels (calendar_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_calendar_levels_metadata_gin ON calendar.calendar_levels USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_calendar_levels_metadata_deleted_at ON calendar.calendar_levels ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_calendar_levels_metadata_created_at ON calendar.calendar_levels ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_calendar_levels_metadata_updated_at ON calendar.calendar_levels ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION calendar.calendar_levels_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_levels_insert_audit ON calendar.calendar_levels;
CREATE TRIGGER calendar_levels_insert_audit BEFORE INSERT ON calendar.calendar_levels
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_levels_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_levels_update_audit ON calendar.calendar_levels;
CREATE TRIGGER calendar_levels_update_audit BEFORE UPDATE ON calendar.calendar_levels
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_levels_audit_timestamp();
