-- Migration: Create calendars table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS calendar;

CREATE TABLE IF NOT EXISTS calendar.calendars (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    date_start DATE NOT NULL,
    date_end DATE NOT NULL,
    is_holiday BOOLEAN NOT NULL DEFAULT FALSE,
    can_everyone_view BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_calendars_company_id_date_start ON calendar.calendars (company_id, date_start);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_calendars_metadata_gin ON calendar.calendars USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_calendars_metadata_deleted_at ON calendar.calendars ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_calendars_metadata_created_at ON calendar.calendars ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_calendars_metadata_updated_at ON calendar.calendars ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION calendar.calendars_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendars_insert_audit ON calendar.calendars;
CREATE TRIGGER calendars_insert_audit BEFORE INSERT ON calendar.calendars
    FOR EACH ROW EXECUTE FUNCTION calendar.calendars_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendars_update_audit ON calendar.calendars;
CREATE TRIGGER calendars_update_audit BEFORE UPDATE ON calendar.calendars
    FOR EACH ROW EXECUTE FUNCTION calendar.calendars_audit_timestamp();
