-- Company fence posture for calendar module (ADR-0014: strict)
-- Generated by metaphor-schema. Every entity here carries company_id and is fenced
-- strict: a session sees only rows whose company_id equals the request-scoped
-- company (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero
-- rows (fail-closed). These tables shipped company_id without a policy since the
-- pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). Requires the app to connect as a non-superuser
-- role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for calendar.calendar_branches
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE calendar.calendar_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar.calendar_branches FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS calendar_branches_company_isolation ON calendar.calendar_branches;
CREATE POLICY calendar_branches_company_isolation ON calendar.calendar_branches
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for calendar.calendars
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE calendar.calendars ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar.calendars FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS calendars_company_isolation ON calendar.calendars;
CREATE POLICY calendars_company_isolation ON calendar.calendars
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
