-- Revert the ADR-0014 strict company fence for calendar module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS calendar_branches_company_isolation ON calendar.calendar_branches;
ALTER TABLE calendar.calendar_branches NO FORCE ROW LEVEL SECURITY;
ALTER TABLE calendar.calendar_branches DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS calendars_company_isolation ON calendar.calendars;
ALTER TABLE calendar.calendars NO FORCE ROW LEVEL SECURITY;
ALTER TABLE calendar.calendars DISABLE ROW LEVEL SECURITY;
