-- Enum types for calendar module
-- Generated by metaphor-schema

-- Create employment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_status') THEN
        CREATE TYPE employment_status AS ENUM ('permanent', 'contract', 'probation', 'associate');
    END IF;
END
$$;

