-- Audit Triggers Migration for calendar module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Calendar (calendar.calendars)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendars_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendars_insert_audit ON calendar.calendars;
CREATE TRIGGER calendars_insert_audit BEFORE INSERT ON calendar.calendars
    FOR EACH ROW EXECUTE FUNCTION calendar.calendars_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendars_update_audit ON calendar.calendars;
CREATE TRIGGER calendars_update_audit BEFORE UPDATE ON calendar.calendars
    FOR EACH ROW EXECUTE FUNCTION calendar.calendars_audit_timestamp();

-- ==============================================================================
-- Table: CalendarBranch (calendar.calendar_branches)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_branches_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_branches_insert_audit ON calendar.calendar_branches;
CREATE TRIGGER calendar_branches_insert_audit BEFORE INSERT ON calendar.calendar_branches
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_branches_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_branches_update_audit ON calendar.calendar_branches;
CREATE TRIGGER calendar_branches_update_audit BEFORE UPDATE ON calendar.calendar_branches
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_branches_audit_timestamp();

-- ==============================================================================
-- Table: CalendarDepartment (calendar.calendar_departments)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_departments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_departments_insert_audit ON calendar.calendar_departments;
CREATE TRIGGER calendar_departments_insert_audit BEFORE INSERT ON calendar.calendar_departments
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_departments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_departments_update_audit ON calendar.calendar_departments;
CREATE TRIGGER calendar_departments_update_audit BEFORE UPDATE ON calendar.calendar_departments
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_departments_audit_timestamp();

-- ==============================================================================
-- Table: CalendarEmployee (calendar.calendar_employees)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_employees_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_employees_insert_audit ON calendar.calendar_employees;
CREATE TRIGGER calendar_employees_insert_audit BEFORE INSERT ON calendar.calendar_employees
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employees_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_employees_update_audit ON calendar.calendar_employees;
CREATE TRIGGER calendar_employees_update_audit BEFORE UPDATE ON calendar.calendar_employees
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employees_audit_timestamp();

-- ==============================================================================
-- Table: CalendarEmployeeStatus (calendar.calendar_employee_statuses)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_employee_statuses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_employee_statuses_insert_audit ON calendar.calendar_employee_statuses;
CREATE TRIGGER calendar_employee_statuses_insert_audit BEFORE INSERT ON calendar.calendar_employee_statuses
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employee_statuses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_employee_statuses_update_audit ON calendar.calendar_employee_statuses;
CREATE TRIGGER calendar_employee_statuses_update_audit BEFORE UPDATE ON calendar.calendar_employee_statuses
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_employee_statuses_audit_timestamp();

-- ==============================================================================
-- Table: CalendarLevel (calendar.calendar_levels)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_levels_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_levels_insert_audit ON calendar.calendar_levels;
CREATE TRIGGER calendar_levels_insert_audit BEFORE INSERT ON calendar.calendar_levels
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_levels_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_levels_update_audit ON calendar.calendar_levels;
CREATE TRIGGER calendar_levels_update_audit BEFORE UPDATE ON calendar.calendar_levels
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_levels_audit_timestamp();

-- ==============================================================================
-- Table: CalendarPosition (calendar.calendar_positions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_positions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_positions_insert_audit ON calendar.calendar_positions;
CREATE TRIGGER calendar_positions_insert_audit BEFORE INSERT ON calendar.calendar_positions
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_positions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_positions_update_audit ON calendar.calendar_positions;
CREATE TRIGGER calendar_positions_update_audit BEFORE UPDATE ON calendar.calendar_positions
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_positions_audit_timestamp();

-- ==============================================================================
-- Table: CalendarReligion (calendar.calendar_religions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION calendar.calendar_religions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calendar_religions_insert_audit ON calendar.calendar_religions;
CREATE TRIGGER calendar_religions_insert_audit BEFORE INSERT ON calendar.calendar_religions
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_religions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calendar_religions_update_audit ON calendar.calendar_religions;
CREATE TRIGGER calendar_religions_update_audit BEFORE UPDATE ON calendar.calendar_religions
    FOR EACH ROW EXECUTE FUNCTION calendar.calendar_religions_audit_timestamp();

