//! Domain events for CalendarEventException entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarEventException;

/// Domain events for CalendarEventException — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarEventException>)` variant.
pub type CalendarEventExceptionEvent = CrudEvent<CalendarEventException>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarEventException events.
pub type CalendarEventExceptionEventPublisher = Arc<dyn CrudEventPublisher<CalendarEventException> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarEventExceptionEventPublisher = NoOpCrudEventPublisher<CalendarEventException>;
