//! Domain events for Calendar entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Calendar;

/// Domain events for Calendar — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Calendar>)` variant.
pub type CalendarEvent = CrudEvent<Calendar>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Calendar events.
pub type CalendarEventPublisher = Arc<dyn CrudEventPublisher<Calendar> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarEventPublisher = NoOpCrudEventPublisher<Calendar>;
