//! Domain events for CalendarEmployeeStatus entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarEmployeeStatus;

/// Domain events for CalendarEmployeeStatus — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarEmployeeStatus>)` variant.
pub type CalendarEmployeeStatusEvent = CrudEvent<CalendarEmployeeStatus>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarEmployeeStatus events.
pub type CalendarEmployeeStatusEventPublisher = Arc<dyn CrudEventPublisher<CalendarEmployeeStatus> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarEmployeeStatusEventPublisher = NoOpCrudEventPublisher<CalendarEmployeeStatus>;
