//! Event handler trait for CalendarEventAttendee events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarEventAttendeeEvent;

/// Event handler for CalendarEventAttendee events.
/// Implement this trait to react to CalendarEventAttendee lifecycle events.
pub trait CalendarEventAttendeeEventHandler: EventHandler<CalendarEventAttendeeEvent> {}
