//! Domain events for CalendarLevel entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarLevel;

/// Domain events for CalendarLevel — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarLevel>)` variant.
pub type CalendarLevelEvent = CrudEvent<CalendarLevel>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarLevel events.
pub type CalendarLevelEventPublisher = Arc<dyn CrudEventPublisher<CalendarLevel> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarLevelEventPublisher = NoOpCrudEventPublisher<CalendarLevel>;
