//! Domain events for CalendarPosition entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarPosition;

/// Domain events for CalendarPosition — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarPosition>)` variant.
pub type CalendarPositionEvent = CrudEvent<CalendarPosition>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarPosition events.
pub type CalendarPositionEventPublisher = Arc<dyn CrudEventPublisher<CalendarPosition> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarPositionEventPublisher = NoOpCrudEventPublisher<CalendarPosition>;
