//! Event handler trait for CalendarDepartment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarDepartmentEvent;

/// Event handler for CalendarDepartment events.
/// Implement this trait to react to CalendarDepartment lifecycle events.
pub trait CalendarDepartmentEventHandler: EventHandler<CalendarDepartmentEvent> {}
