//! Event handler trait for CalendarLevel events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarLevelEvent;

/// Event handler for CalendarLevel events.
/// Implement this trait to react to CalendarLevel lifecycle events.
pub trait CalendarLevelEventHandler: EventHandler<CalendarLevelEvent> {}
