//! Domain events for CalendarReligion entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarReligion;

/// Domain events for CalendarReligion — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarReligion>)` variant.
pub type CalendarReligionEvent = CrudEvent<CalendarReligion>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarReligion events.
pub type CalendarReligionEventPublisher = Arc<dyn CrudEventPublisher<CalendarReligion> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarReligionEventPublisher = NoOpCrudEventPublisher<CalendarReligion>;
