//! Event handler trait for CalendarLevel events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarLevelEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarLevel events.
/// Implement this trait to react to CalendarLevel lifecycle events.
pub trait CalendarLevelEventHandler: EventHandler<CalendarLevelEvent> {}
