//! Event handler trait for Calendar events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarEvent;
use backbone_messaging::EventHandler;

/// Event handler for Calendar events.
/// Implement this trait to react to Calendar lifecycle events.
pub trait CalendarEventHandler: EventHandler<CalendarEvent> {}
