//! Event handler trait for CalendarEmployee events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarEmployeeEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarEmployee events.
/// Implement this trait to react to CalendarEmployee lifecycle events.
pub trait CalendarEmployeeEventHandler: EventHandler<CalendarEmployeeEvent> {}
