//! Event handler trait for CalendarEventSeries events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarEventSeriesEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarEventSeries events.
/// Implement this trait to react to CalendarEventSeries lifecycle events.
pub trait CalendarEventSeriesEventHandler: EventHandler<CalendarEventSeriesEvent> {}
