//! Domain events for CalendarEmployee entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarEmployee;

/// Domain events for CalendarEmployee — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarEmployee>)` variant.
pub type CalendarEmployeeEvent = CrudEvent<CalendarEmployee>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarEmployee events.
pub type CalendarEmployeeEventPublisher = Arc<dyn CrudEventPublisher<CalendarEmployee> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarEmployeeEventPublisher = NoOpCrudEventPublisher<CalendarEmployee>;
