//! Event handler trait for CalendarReligion events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarReligionEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarReligion events.
/// Implement this trait to react to CalendarReligion lifecycle events.
pub trait CalendarReligionEventHandler: EventHandler<CalendarReligionEvent> {}
