//! Event handler trait for CalendarEventException events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarEventExceptionEvent;

/// Event handler for CalendarEventException events.
/// Implement this trait to react to CalendarEventException lifecycle events.
pub trait CalendarEventExceptionEventHandler: EventHandler<CalendarEventExceptionEvent> {}
