//! Event handler trait for CalendarEmployeeStatus events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarEmployeeStatusEvent;

/// Event handler for CalendarEmployeeStatus events.
/// Implement this trait to react to CalendarEmployeeStatus lifecycle events.
pub trait CalendarEmployeeStatusEventHandler: EventHandler<CalendarEmployeeStatusEvent> {}
