//! Event handler trait for CalendarPosition events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarPositionEvent;

/// Event handler for CalendarPosition events.
/// Implement this trait to react to CalendarPosition lifecycle events.
pub trait CalendarPositionEventHandler: EventHandler<CalendarPositionEvent> {}
