//! Event handler trait for CalendarPosition events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarPositionEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarPosition events.
/// Implement this trait to react to CalendarPosition lifecycle events.
pub trait CalendarPositionEventHandler: EventHandler<CalendarPositionEvent> {}
