//! Event handler trait for CalendarBranch events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CalendarBranchEvent;

/// Event handler for CalendarBranch events.
/// Implement this trait to react to CalendarBranch lifecycle events.
pub trait CalendarBranchEventHandler: EventHandler<CalendarBranchEvent> {}
