//! Event handler trait for CalendarEvent events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CalendarEventEvent;
use backbone_messaging::EventHandler;

/// Event handler for CalendarEvent events.
/// Implement this trait to react to CalendarEvent lifecycle events.
pub trait CalendarEventEventHandler: EventHandler<CalendarEventEvent> {}
