//! Domain events for CalendarEventSeries entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CalendarEventSeries;

/// Domain events for CalendarEventSeries — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CalendarEventSeries>)` variant.
pub type CalendarEventSeriesEvent = CrudEvent<CalendarEventSeries>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CalendarEventSeries events.
pub type CalendarEventSeriesEventPublisher = Arc<dyn CrudEventPublisher<CalendarEventSeries> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCalendarEventSeriesEventPublisher = NoOpCrudEventPublisher<CalendarEventSeries>;
