//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod calendar_events;
pub mod calendar_event_handlers;
pub mod calendar_branch_events;
pub mod calendar_branch_event_handlers;
pub mod calendar_department_events;
pub mod calendar_department_event_handlers;
pub mod calendar_employee_events;
pub mod calendar_employee_event_handlers;
pub mod calendar_employee_status_events;
pub mod calendar_employee_status_event_handlers;
pub mod calendar_level_events;
pub mod calendar_level_event_handlers;
pub mod calendar_position_events;
pub mod calendar_position_event_handlers;
pub mod calendar_religion_events;
pub mod calendar_religion_event_handlers;

pub use calendar_events::{CalendarEvent, CalendarEventPublisher, NoopCalendarEventPublisher};
pub use calendar_event_handlers::CalendarEventHandler;
pub use calendar_branch_events::{CalendarBranchEvent, CalendarBranchEventPublisher, NoopCalendarBranchEventPublisher};
pub use calendar_branch_event_handlers::CalendarBranchEventHandler;
pub use calendar_department_events::{CalendarDepartmentEvent, CalendarDepartmentEventPublisher, NoopCalendarDepartmentEventPublisher};
pub use calendar_department_event_handlers::CalendarDepartmentEventHandler;
pub use calendar_employee_events::{CalendarEmployeeEvent, CalendarEmployeeEventPublisher, NoopCalendarEmployeeEventPublisher};
pub use calendar_employee_event_handlers::CalendarEmployeeEventHandler;
pub use calendar_employee_status_events::{CalendarEmployeeStatusEvent, CalendarEmployeeStatusEventPublisher, NoopCalendarEmployeeStatusEventPublisher};
pub use calendar_employee_status_event_handlers::CalendarEmployeeStatusEventHandler;
pub use calendar_level_events::{CalendarLevelEvent, CalendarLevelEventPublisher, NoopCalendarLevelEventPublisher};
pub use calendar_level_event_handlers::CalendarLevelEventHandler;
pub use calendar_position_events::{CalendarPositionEvent, CalendarPositionEventPublisher, NoopCalendarPositionEventPublisher};
pub use calendar_position_event_handlers::CalendarPositionEventHandler;
pub use calendar_religion_events::{CalendarReligionEvent, CalendarReligionEventPublisher, NoopCalendarReligionEventPublisher};
pub use calendar_religion_event_handlers::CalendarReligionEventHandler;

// <<< CUSTOM
// END CUSTOM
