//! CalendarEmployeeStatus seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CalendarEmployeeStatus data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CALENDAREMPLOYEESTATUS SEEDER
// ============================================================================

/// Seeder for calendar_employee_status
pub struct SeedCalendarEmployeeStatusSeeder;

impl SeedCalendarEmployeeStatusSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCalendarEmployeeStatusSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCalendarEmployeeStatusSeeder {
    fn name(&self) -> &'static str {
        "SeedCalendarEmployeeStatusSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if calendar.calendar_employee_statuses table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM calendar.calendar_employee_statuses")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/calendar_employee_status_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM calendar.calendar_employee_statuses")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
