//! CalendarEventAttendee seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CalendarEventAttendee data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CALENDAREVENTATTENDEE SEEDER
// ============================================================================

/// Seeder for calendar_event_attendee
pub struct SeedCalendarEventAttendeeSeeder;

impl SeedCalendarEventAttendeeSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCalendarEventAttendeeSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCalendarEventAttendeeSeeder {
    fn name(&self) -> &'static str {
        "SeedCalendarEventAttendeeSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if calendar.event_attendees table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM calendar.event_attendees")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/calendar_event_attendee_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM calendar.event_attendees")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
