//! CalendarEventSeries seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CalendarEventSeries data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CALENDAREVENTSERIES SEEDER
// ============================================================================

/// Seeder for calendar_event_series
pub struct SeedCalendarEventSeriesSeeder;

impl SeedCalendarEventSeriesSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCalendarEventSeriesSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCalendarEventSeriesSeeder {
    fn name(&self) -> &'static str {
        "SeedCalendarEventSeriesSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if calendar.event_series table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM calendar.event_series")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/calendar_event_series_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM calendar.event_series")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
