//! CalendarEventException seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CalendarEventException data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CALENDAREVENTEXCEPTION SEEDER
// ============================================================================

/// Seeder for calendar_event_exception
pub struct SeedCalendarEventExceptionSeeder;

impl SeedCalendarEventExceptionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCalendarEventExceptionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCalendarEventExceptionSeeder {
    fn name(&self) -> &'static str {
        "SeedCalendarEventExceptionSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if calendar.event_exceptions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM calendar.event_exceptions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/calendar_event_exception_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM calendar.event_exceptions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
