//! Database seeders for the calendar module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod calendar_seeder;
mod calendar_branch_seeder;
mod calendar_department_seeder;
mod calendar_employee_seeder;
mod calendar_employee_status_seeder;
mod calendar_event_seeder;
mod calendar_event_attendee_seeder;
mod calendar_event_exception_seeder;
mod calendar_event_series_seeder;
mod calendar_level_seeder;
mod calendar_position_seeder;
mod calendar_religion_seeder;

pub use calendar_seeder::SeedCalendarSeeder;
pub use calendar_branch_seeder::SeedCalendarBranchSeeder;
pub use calendar_department_seeder::SeedCalendarDepartmentSeeder;
pub use calendar_employee_seeder::SeedCalendarEmployeeSeeder;
pub use calendar_employee_status_seeder::SeedCalendarEmployeeStatusSeeder;
pub use calendar_event_seeder::SeedCalendarEventSeeder;
pub use calendar_event_attendee_seeder::SeedCalendarEventAttendeeSeeder;
pub use calendar_event_exception_seeder::SeedCalendarEventExceptionSeeder;
pub use calendar_event_series_seeder::SeedCalendarEventSeriesSeeder;
pub use calendar_level_seeder::SeedCalendarLevelSeeder;
pub use calendar_position_seeder::SeedCalendarPositionSeeder;
pub use calendar_religion_seeder::SeedCalendarReligionSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
