//! Repository trait for CalendarReligion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarReligion aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CalendarReligion;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarReligionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarReligionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarReligionPaginatedResult {
    pub data: Vec<CalendarReligion>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarReligionFilter {
    pub calendar_id: Option<Uuid>,
    pub religion_id: Option<Uuid>,
}

impl CalendarReligionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.religion_id.is_some()
    }
}

/// Repository trait for CalendarReligion aggregate
///
/// This trait defines the persistence contract for CalendarReligion entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarReligionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_religion entity
    async fn save(&self, entity: &CalendarReligion) -> Result<CalendarReligion>;

    /// Find calendar_religion by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarReligion>>;

    /// Find all calendar_religion entities
    async fn find_all(&self) -> Result<Vec<CalendarReligion>>;

    /// Update calendar_religion by ID
    async fn update(&self, id: &str, entity: &CalendarReligion) -> Result<Option<CalendarReligion>>;

    /// Delete calendar_religion by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_religion with pagination
    async fn list(&self, params: CalendarReligionPaginationParams) -> Result<CalendarReligionPaginatedResult>;

    /// List calendar_religion with pagination and filters
    async fn list_with_filters(&self, params: CalendarReligionPaginationParams, filters: CalendarReligionFilter) -> Result<CalendarReligionPaginatedResult>;

    /// Count all calendar_religion entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_religion entities matching filters
    async fn count_with_filters(&self, filters: CalendarReligionFilter) -> Result<u64>;

    /// Check if calendar_religion exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_religion by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_religion by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarReligion>>;

    /// List soft-deleted calendar_religion entities
    async fn list_deleted(&self, params: CalendarReligionPaginationParams) -> Result<CalendarReligionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_religion entities
    async fn bulk_save(&self, entities: &[CalendarReligion]) -> Result<Vec<CalendarReligion>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
