//! Repository trait for CalendarEmployeeStatus aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarEmployeeStatus aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{CalendarEmployeeStatus, EmploymentStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEmployeeStatusPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarEmployeeStatusPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarEmployeeStatusPaginatedResult {
    pub data: Vec<CalendarEmployeeStatus>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEmployeeStatusFilter {
    pub calendar_id: Option<Uuid>,
    pub employment_status: Option<EmploymentStatus>,
}

impl CalendarEmployeeStatusFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.employment_status.is_some()
    }
}

/// Repository trait for CalendarEmployeeStatus aggregate
///
/// This trait defines the persistence contract for CalendarEmployeeStatus entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarEmployeeStatusRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_employee_status entity
    async fn save(&self, entity: &CalendarEmployeeStatus) -> Result<CalendarEmployeeStatus>;

    /// Find calendar_employee_status by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarEmployeeStatus>>;

    /// Find all calendar_employee_status entities
    async fn find_all(&self) -> Result<Vec<CalendarEmployeeStatus>>;

    /// Update calendar_employee_status by ID
    async fn update(&self, id: &str, entity: &CalendarEmployeeStatus) -> Result<Option<CalendarEmployeeStatus>>;

    /// Delete calendar_employee_status by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_employee_status with pagination
    async fn list(&self, params: CalendarEmployeeStatusPaginationParams) -> Result<CalendarEmployeeStatusPaginatedResult>;

    /// List calendar_employee_status with pagination and filters
    async fn list_with_filters(&self, params: CalendarEmployeeStatusPaginationParams, filters: CalendarEmployeeStatusFilter) -> Result<CalendarEmployeeStatusPaginatedResult>;

    /// Count all calendar_employee_status entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_employee_status entities matching filters
    async fn count_with_filters(&self, filters: CalendarEmployeeStatusFilter) -> Result<u64>;

    /// Check if calendar_employee_status exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_employee_status by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_employee_status by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarEmployeeStatus>>;

    /// List soft-deleted calendar_employee_status entities
    async fn list_deleted(&self, params: CalendarEmployeeStatusPaginationParams) -> Result<CalendarEmployeeStatusPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_employee_status entities
    async fn bulk_save(&self, entities: &[CalendarEmployeeStatus]) -> Result<Vec<CalendarEmployeeStatus>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
