//! Repository trait for CalendarDepartment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarDepartment aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CalendarDepartment;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarDepartmentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarDepartmentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarDepartmentPaginatedResult {
    pub data: Vec<CalendarDepartment>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarDepartmentFilter {
    pub calendar_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
}

impl CalendarDepartmentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.department_id.is_some()
    }
}

/// Repository trait for CalendarDepartment aggregate
///
/// This trait defines the persistence contract for CalendarDepartment entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarDepartmentRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_department entity
    async fn save(&self, entity: &CalendarDepartment) -> Result<CalendarDepartment>;

    /// Find calendar_department by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarDepartment>>;

    /// Find all calendar_department entities
    async fn find_all(&self) -> Result<Vec<CalendarDepartment>>;

    /// Update calendar_department by ID
    async fn update(&self, id: &str, entity: &CalendarDepartment) -> Result<Option<CalendarDepartment>>;

    /// Delete calendar_department by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_department with pagination
    async fn list(&self, params: CalendarDepartmentPaginationParams) -> Result<CalendarDepartmentPaginatedResult>;

    /// List calendar_department with pagination and filters
    async fn list_with_filters(&self, params: CalendarDepartmentPaginationParams, filters: CalendarDepartmentFilter) -> Result<CalendarDepartmentPaginatedResult>;

    /// Count all calendar_department entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_department entities matching filters
    async fn count_with_filters(&self, filters: CalendarDepartmentFilter) -> Result<u64>;

    /// Check if calendar_department exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_department by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_department by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarDepartment>>;

    /// List soft-deleted calendar_department entities
    async fn list_deleted(&self, params: CalendarDepartmentPaginationParams) -> Result<CalendarDepartmentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_department entities
    async fn bulk_save(&self, entities: &[CalendarDepartment]) -> Result<Vec<CalendarDepartment>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
