//! Repository trait for CalendarEmployee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarEmployee aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CalendarEmployee;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEmployeePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarEmployeePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarEmployeePaginatedResult {
    pub data: Vec<CalendarEmployee>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEmployeeFilter {
    pub calendar_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
}

impl CalendarEmployeeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.employee_id.is_some()
    }
}

/// Repository trait for CalendarEmployee aggregate
///
/// This trait defines the persistence contract for CalendarEmployee entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarEmployeeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_employee entity
    async fn save(&self, entity: &CalendarEmployee) -> Result<CalendarEmployee>;

    /// Find calendar_employee by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarEmployee>>;

    /// Find all calendar_employee entities
    async fn find_all(&self) -> Result<Vec<CalendarEmployee>>;

    /// Update calendar_employee by ID
    async fn update(&self, id: &str, entity: &CalendarEmployee) -> Result<Option<CalendarEmployee>>;

    /// Delete calendar_employee by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_employee with pagination
    async fn list(&self, params: CalendarEmployeePaginationParams) -> Result<CalendarEmployeePaginatedResult>;

    /// List calendar_employee with pagination and filters
    async fn list_with_filters(&self, params: CalendarEmployeePaginationParams, filters: CalendarEmployeeFilter) -> Result<CalendarEmployeePaginatedResult>;

    /// Count all calendar_employee entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_employee entities matching filters
    async fn count_with_filters(&self, filters: CalendarEmployeeFilter) -> Result<u64>;

    /// Check if calendar_employee exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_employee by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_employee by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarEmployee>>;

    /// List soft-deleted calendar_employee entities
    async fn list_deleted(&self, params: CalendarEmployeePaginationParams) -> Result<CalendarEmployeePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_employee entities
    async fn bulk_save(&self, entities: &[CalendarEmployee]) -> Result<Vec<CalendarEmployee>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
