//! Repository trait for CalendarLevel aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarLevel aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CalendarLevel;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarLevelPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarLevelPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarLevelPaginatedResult {
    pub data: Vec<CalendarLevel>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarLevelFilter {
    pub calendar_id: Option<Uuid>,
    pub level_id: Option<Uuid>,
}

impl CalendarLevelFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.level_id.is_some()
    }
}

/// Repository trait for CalendarLevel aggregate
///
/// This trait defines the persistence contract for CalendarLevel entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarLevelRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_level entity
    async fn save(&self, entity: &CalendarLevel) -> Result<CalendarLevel>;

    /// Find calendar_level by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarLevel>>;

    /// Find all calendar_level entities
    async fn find_all(&self) -> Result<Vec<CalendarLevel>>;

    /// Update calendar_level by ID
    async fn update(&self, id: &str, entity: &CalendarLevel) -> Result<Option<CalendarLevel>>;

    /// Delete calendar_level by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_level with pagination
    async fn list(&self, params: CalendarLevelPaginationParams) -> Result<CalendarLevelPaginatedResult>;

    /// List calendar_level with pagination and filters
    async fn list_with_filters(&self, params: CalendarLevelPaginationParams, filters: CalendarLevelFilter) -> Result<CalendarLevelPaginatedResult>;

    /// Count all calendar_level entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_level entities matching filters
    async fn count_with_filters(&self, filters: CalendarLevelFilter) -> Result<u64>;

    /// Check if calendar_level exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_level by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_level by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarLevel>>;

    /// List soft-deleted calendar_level entities
    async fn list_deleted(&self, params: CalendarLevelPaginationParams) -> Result<CalendarLevelPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_level entities
    async fn bulk_save(&self, entities: &[CalendarLevel]) -> Result<Vec<CalendarLevel>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
