//! Repository trait for CalendarEventSeries aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarEventSeries aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{CalendarEventSeries, EventRecurrenceFreq};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEventSeriesPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarEventSeriesPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarEventSeriesPaginatedResult {
    pub data: Vec<CalendarEventSeries>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEventSeriesFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub freq: Option<EventRecurrenceFreq>,
    pub by_weekday: Option<String>,
    pub by_monthday: Option<String>,
    pub base_event_id: Option<Uuid>,
}

impl CalendarEventSeriesFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.freq.is_some() || self.by_weekday.is_some() || self.by_monthday.is_some() || self.base_event_id.is_some()
    }
}

/// Repository trait for CalendarEventSeries aggregate
///
/// This trait defines the persistence contract for CalendarEventSeries entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarEventSeriesRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_event_series entity
    async fn save(&self, entity: &CalendarEventSeries) -> Result<CalendarEventSeries>;

    /// Find calendar_event_series by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarEventSeries>>;

    /// Find all calendar_event_series entities
    async fn find_all(&self) -> Result<Vec<CalendarEventSeries>>;

    /// Update calendar_event_series by ID
    async fn update(&self, id: &str, entity: &CalendarEventSeries) -> Result<Option<CalendarEventSeries>>;

    /// Delete calendar_event_series by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_event_series with pagination
    async fn list(&self, params: CalendarEventSeriesPaginationParams) -> Result<CalendarEventSeriesPaginatedResult>;

    /// List calendar_event_series with pagination and filters
    async fn list_with_filters(&self, params: CalendarEventSeriesPaginationParams, filters: CalendarEventSeriesFilter) -> Result<CalendarEventSeriesPaginatedResult>;

    /// Count all calendar_event_series entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_event_series entities matching filters
    async fn count_with_filters(&self, filters: CalendarEventSeriesFilter) -> Result<u64>;

    /// Check if calendar_event_series exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_event_series by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_event_series by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarEventSeries>>;

    /// List soft-deleted calendar_event_series entities
    async fn list_deleted(&self, params: CalendarEventSeriesPaginationParams) -> Result<CalendarEventSeriesPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_event_series entities
    async fn bulk_save(&self, entities: &[CalendarEventSeries]) -> Result<Vec<CalendarEventSeries>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
