//! Repository trait for CalendarBranch aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarBranch aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CalendarBranch;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarBranchPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarBranchPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarBranchPaginatedResult {
    pub data: Vec<CalendarBranch>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarBranchFilter {
    pub calendar_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
}

impl CalendarBranchFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.calendar_id.is_some() || self.company_id.is_some() || self.branch_id.is_some()
    }
}

/// Repository trait for CalendarBranch aggregate
///
/// This trait defines the persistence contract for CalendarBranch entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarBranchRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_branch entity
    async fn save(&self, entity: &CalendarBranch) -> Result<CalendarBranch>;

    /// Find calendar_branch by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarBranch>>;

    /// Find all calendar_branch entities
    async fn find_all(&self) -> Result<Vec<CalendarBranch>>;

    /// Update calendar_branch by ID
    async fn update(&self, id: &str, entity: &CalendarBranch) -> Result<Option<CalendarBranch>>;

    /// Delete calendar_branch by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_branch with pagination
    async fn list(&self, params: CalendarBranchPaginationParams) -> Result<CalendarBranchPaginatedResult>;

    /// List calendar_branch with pagination and filters
    async fn list_with_filters(&self, params: CalendarBranchPaginationParams, filters: CalendarBranchFilter) -> Result<CalendarBranchPaginatedResult>;

    /// Count all calendar_branch entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_branch entities matching filters
    async fn count_with_filters(&self, filters: CalendarBranchFilter) -> Result<u64>;

    /// Check if calendar_branch exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_branch by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_branch by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarBranch>>;

    /// List soft-deleted calendar_branch entities
    async fn list_deleted(&self, params: CalendarBranchPaginationParams) -> Result<CalendarBranchPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_branch entities
    async fn bulk_save(&self, entities: &[CalendarBranch]) -> Result<Vec<CalendarBranch>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
