//! Repository trait for CalendarEvent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CalendarEvent aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{CalendarEvent, EventPrivacy};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEventPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarEventPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarEventPaginatedResult {
    pub data: Vec<CalendarEvent>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarEventFilter {
    pub company_id: Option<Uuid>,
    pub series_id: Option<Uuid>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub privacy: Option<EventPrivacy>,
    pub organizer_user_id: Option<Uuid>,
    pub location: Option<String>,
}

impl CalendarEventFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.series_id.is_some() || self.title.is_some() || self.description.is_some() || self.privacy.is_some() || self.organizer_user_id.is_some() || self.location.is_some()
    }
}

/// Repository trait for CalendarEvent aggregate
///
/// This trait defines the persistence contract for CalendarEvent entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarEventRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar_event entity
    async fn save(&self, entity: &CalendarEvent) -> Result<CalendarEvent>;

    /// Find calendar_event by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CalendarEvent>>;

    /// Find all calendar_event entities
    async fn find_all(&self) -> Result<Vec<CalendarEvent>>;

    /// Update calendar_event by ID
    async fn update(&self, id: &str, entity: &CalendarEvent) -> Result<Option<CalendarEvent>>;

    /// Delete calendar_event by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar_event with pagination
    async fn list(&self, params: CalendarEventPaginationParams) -> Result<CalendarEventPaginatedResult>;

    /// List calendar_event with pagination and filters
    async fn list_with_filters(&self, params: CalendarEventPaginationParams, filters: CalendarEventFilter) -> Result<CalendarEventPaginatedResult>;

    /// Count all calendar_event entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar_event entities matching filters
    async fn count_with_filters(&self, filters: CalendarEventFilter) -> Result<u64>;

    /// Check if calendar_event exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar_event by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar_event by ID
    async fn restore(&self, id: &str) -> Result<Option<CalendarEvent>>;

    /// List soft-deleted calendar_event entities
    async fn list_deleted(&self, params: CalendarEventPaginationParams) -> Result<CalendarEventPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar_event entities
    async fn bulk_save(&self, entities: &[CalendarEvent]) -> Result<Vec<CalendarEvent>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
