//! Repository trait for Calendar aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Calendar aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Calendar;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CalendarPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CalendarPaginatedResult {
    pub data: Vec<Calendar>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CalendarFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub is_holiday: Option<bool>,
    pub can_everyone_view: Option<bool>,
    pub note: Option<String>,
}

impl CalendarFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_holiday.is_some() || self.can_everyone_view.is_some() || self.note.is_some()
    }
}

/// Repository trait for Calendar aggregate
///
/// This trait defines the persistence contract for Calendar entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CalendarRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new calendar entity
    async fn save(&self, entity: &Calendar) -> Result<Calendar>;

    /// Find calendar by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Calendar>>;

    /// Find all calendar entities
    async fn find_all(&self) -> Result<Vec<Calendar>>;

    /// Update calendar by ID
    async fn update(&self, id: &str, entity: &Calendar) -> Result<Option<Calendar>>;

    /// Delete calendar by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List calendar with pagination
    async fn list(&self, params: CalendarPaginationParams) -> Result<CalendarPaginatedResult>;

    /// List calendar with pagination and filters
    async fn list_with_filters(&self, params: CalendarPaginationParams, filters: CalendarFilter) -> Result<CalendarPaginatedResult>;

    /// Count all calendar entities
    async fn count(&self) -> Result<u64>;

    /// Count calendar entities matching filters
    async fn count_with_filters(&self, filters: CalendarFilter) -> Result<u64>;

    /// Check if calendar exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete calendar by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted calendar by ID
    async fn restore(&self, id: &str) -> Result<Option<Calendar>>;

    /// List soft-deleted calendar entities
    async fn list_deleted(&self, params: CalendarPaginationParams) -> Result<CalendarPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save calendar entities
    async fn bulk_save(&self, entities: &[Calendar]) -> Result<Vec<Calendar>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
