//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod calendar_repository;
pub mod calendar_branch_repository;
pub mod calendar_department_repository;
pub mod calendar_employee_repository;
pub mod calendar_employee_status_repository;
pub mod calendar_event_repository;
pub mod calendar_event_attendee_repository;
pub mod calendar_event_exception_repository;
pub mod calendar_event_series_repository;
pub mod calendar_level_repository;
pub mod calendar_position_repository;
pub mod calendar_religion_repository;

// Re-exports
pub use calendar_repository::{
    CalendarRepository,
    CalendarPaginationParams,
    CalendarPaginatedResult,
    CalendarFilter,
};
pub use calendar_branch_repository::{
    CalendarBranchRepository,
    CalendarBranchPaginationParams,
    CalendarBranchPaginatedResult,
    CalendarBranchFilter,
};
pub use calendar_department_repository::{
    CalendarDepartmentRepository,
    CalendarDepartmentPaginationParams,
    CalendarDepartmentPaginatedResult,
    CalendarDepartmentFilter,
};
pub use calendar_employee_repository::{
    CalendarEmployeeRepository,
    CalendarEmployeePaginationParams,
    CalendarEmployeePaginatedResult,
    CalendarEmployeeFilter,
};
pub use calendar_employee_status_repository::{
    CalendarEmployeeStatusRepository,
    CalendarEmployeeStatusPaginationParams,
    CalendarEmployeeStatusPaginatedResult,
    CalendarEmployeeStatusFilter,
};
pub use calendar_event_repository::{
    CalendarEventRepository,
    CalendarEventPaginationParams,
    CalendarEventPaginatedResult,
    CalendarEventFilter,
};
pub use calendar_event_attendee_repository::{
    CalendarEventAttendeeRepository,
    CalendarEventAttendeePaginationParams,
    CalendarEventAttendeePaginatedResult,
    CalendarEventAttendeeFilter,
};
pub use calendar_event_exception_repository::{
    CalendarEventExceptionRepository,
    CalendarEventExceptionPaginationParams,
    CalendarEventExceptionPaginatedResult,
    CalendarEventExceptionFilter,
};
pub use calendar_event_series_repository::{
    CalendarEventSeriesRepository,
    CalendarEventSeriesPaginationParams,
    CalendarEventSeriesPaginatedResult,
    CalendarEventSeriesFilter,
};
pub use calendar_level_repository::{
    CalendarLevelRepository,
    CalendarLevelPaginationParams,
    CalendarLevelPaginatedResult,
    CalendarLevelFilter,
};
pub use calendar_position_repository::{
    CalendarPositionRepository,
    CalendarPositionPaginationParams,
    CalendarPositionPaginatedResult,
    CalendarPositionFilter,
};
pub use calendar_religion_repository::{
    CalendarReligionRepository,
    CalendarReligionPaginationParams,
    CalendarReligionPaginatedResult,
    CalendarReligionFilter,
};
