//! Repository for CalendarEmployee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CalendarEmployee, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CalendarEmployee;

/// Table name for CalendarEmployee entities
pub const TABLE_NAME: &str = "calendar.calendar_employees";

/// Repository for CalendarEmployee entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CalendarEmployeeRepository(
    backbone_orm::GenericCrudRepository<CalendarEmployee, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CalendarEmployeeRepository {
    type Target = backbone_orm::GenericCrudRepository<CalendarEmployee, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CalendarEmployeeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CalendarEmployeeRepository, CalendarEmployee, soft_delete);
