//! Repository for CalendarEmployeeStatus entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CalendarEmployeeStatus, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CalendarEmployeeStatus;

/// Table name for CalendarEmployeeStatus entities
pub const TABLE_NAME: &str = "calendar.calendar_employee_statuses";

/// Repository for CalendarEmployeeStatus entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CalendarEmployeeStatusRepository(
    backbone_orm::GenericCrudRepository<CalendarEmployeeStatus, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CalendarEmployeeStatusRepository {
    type Target = backbone_orm::GenericCrudRepository<CalendarEmployeeStatus, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CalendarEmployeeStatusRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CalendarEmployeeStatusRepository, CalendarEmployeeStatus, soft_delete);
