//! Repository for CalendarBranch entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CalendarBranch, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CalendarBranch;

/// Table name for CalendarBranch entities
pub const TABLE_NAME: &str = "calendar.calendar_branches";

/// Repository for CalendarBranch entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CalendarBranchRepository(
    backbone_orm::GenericCrudRepository<CalendarBranch, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CalendarBranchRepository {
    type Target = backbone_orm::GenericCrudRepository<CalendarBranch, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CalendarBranchRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CalendarBranchRepository, CalendarBranch, soft_delete);
