//! Validator for CalendarEventException entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarEventException>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CalendarEventException;

/// Validator type alias for CalendarEventException entities.
pub type CalendarEventExceptionValidator = EntityValidator<CalendarEventException>;

/// Build a validator for CalendarEventException with all schema-defined field rules.
pub fn calendar_event_exception_validator() -> CalendarEventExceptionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
