//! Validator for CalendarReligion entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarReligion>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CalendarReligion;

/// Validator type alias for CalendarReligion entities.
pub type CalendarReligionValidator = EntityValidator<CalendarReligion>;

/// Build a validator for CalendarReligion with all schema-defined field rules.
pub fn calendar_religion_validator() -> CalendarReligionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
