//! Validator for CalendarEmployeeStatus entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarEmployeeStatus>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CalendarEmployeeStatus;

/// Validator type alias for CalendarEmployeeStatus entities.
pub type CalendarEmployeeStatusValidator = EntityValidator<CalendarEmployeeStatus>;

/// Build a validator for CalendarEmployeeStatus with all schema-defined field rules.
pub fn calendar_employee_status_validator() -> CalendarEmployeeStatusValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
