//! Validator for CalendarDepartment entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarDepartment>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::CalendarDepartment;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for CalendarDepartment entities.
pub type CalendarDepartmentValidator = EntityValidator<CalendarDepartment>;

/// Build a validator for CalendarDepartment with all schema-defined field rules.
pub fn calendar_department_validator() -> CalendarDepartmentValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
