//! Validator for CalendarEventAttendee entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarEventAttendee>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::CalendarEventAttendee;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for CalendarEventAttendee entities.
pub type CalendarEventAttendeeValidator = EntityValidator<CalendarEventAttendee>;

/// Build a validator for CalendarEventAttendee with all schema-defined field rules.
pub fn calendar_event_attendee_validator() -> CalendarEventAttendeeValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
