//! Validator for CalendarLevel entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarLevel>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CalendarLevel;

/// Validator type alias for CalendarLevel entities.
pub type CalendarLevelValidator = EntityValidator<CalendarLevel>;

/// Build a validator for CalendarLevel with all schema-defined field rules.
pub fn calendar_level_validator() -> CalendarLevelValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
