//! Validator for CalendarEmployee entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarEmployee>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::CalendarEmployee;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for CalendarEmployee entities.
pub type CalendarEmployeeValidator = EntityValidator<CalendarEmployee>;

/// Build a validator for CalendarEmployee with all schema-defined field rules.
pub fn calendar_employee_validator() -> CalendarEmployeeValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
