//! Validator for CalendarBranch entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CalendarBranch>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CalendarBranch;

/// Validator type alias for CalendarBranch entities.
pub type CalendarBranchValidator = EntityValidator<CalendarBranch>;

/// Build a validator for CalendarBranch with all schema-defined field rules.
pub fn calendar_branch_validator() -> CalendarBranchValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
