//! Validator for Calendar entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Calendar>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Calendar;

/// Validator type alias for Calendar entities.
pub type CalendarValidator = EntityValidator<Calendar>;

/// Build a validator for Calendar with all schema-defined field rules.
pub fn calendar_validator() -> CalendarValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Calendar| &e.name))
        .rule(OptionalNotBlank::new("note", |e: &Calendar| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
