//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod calendar_validator;
pub mod calendar_branch_validator;
pub mod calendar_department_validator;
pub mod calendar_employee_validator;
pub mod calendar_employee_status_validator;
pub mod calendar_level_validator;
pub mod calendar_position_validator;
pub mod calendar_religion_validator;

pub use calendar_validator::{CalendarValidator, calendar_validator};
pub use calendar_branch_validator::{CalendarBranchValidator, calendar_branch_validator};
pub use calendar_department_validator::{CalendarDepartmentValidator, calendar_department_validator};
pub use calendar_employee_validator::{CalendarEmployeeValidator, calendar_employee_validator};
pub use calendar_employee_status_validator::{CalendarEmployeeStatusValidator, calendar_employee_status_validator};
pub use calendar_level_validator::{CalendarLevelValidator, calendar_level_validator};
pub use calendar_position_validator::{CalendarPositionValidator, calendar_position_validator};
pub use calendar_religion_validator::{CalendarReligionValidator, calendar_religion_validator};

// <<< CUSTOM
// END CUSTOM
