//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{EntityValidator, ValidationError, ValidationErrors, ValidationResult};

pub mod calendar_branch_validator;
pub mod calendar_department_validator;
pub mod calendar_employee_status_validator;
pub mod calendar_employee_validator;
pub mod calendar_event_attendee_validator;
pub mod calendar_event_exception_validator;
pub mod calendar_event_series_validator;
pub mod calendar_event_validator;
pub mod calendar_level_validator;
pub mod calendar_position_validator;
pub mod calendar_religion_validator;
pub mod calendar_validator;

pub use calendar_branch_validator::{calendar_branch_validator, CalendarBranchValidator};
pub use calendar_department_validator::{
    calendar_department_validator, CalendarDepartmentValidator,
};
pub use calendar_employee_status_validator::{
    calendar_employee_status_validator, CalendarEmployeeStatusValidator,
};
pub use calendar_employee_validator::{calendar_employee_validator, CalendarEmployeeValidator};
pub use calendar_event_attendee_validator::{
    calendar_event_attendee_validator, CalendarEventAttendeeValidator,
};
pub use calendar_event_exception_validator::{
    calendar_event_exception_validator, CalendarEventExceptionValidator,
};
pub use calendar_event_series_validator::{
    calendar_event_series_validator, CalendarEventSeriesValidator,
};
pub use calendar_event_validator::{calendar_event_validator, CalendarEventValidator};
pub use calendar_level_validator::{calendar_level_validator, CalendarLevelValidator};
pub use calendar_position_validator::{calendar_position_validator, CalendarPositionValidator};
pub use calendar_religion_validator::{calendar_religion_validator, CalendarReligionValidator};
pub use calendar_validator::{calendar_validator, CalendarValidator};

// <<< CUSTOM
// END CUSTOM
