//! Auth configuration for CalendarDepartment handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarDepartment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarDepartmentService;
use crate::domain::entity::CalendarDepartment;

/// Permission string constants for CalendarDepartment operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_department:list";
    pub const READ:        &str = "calendar_department:read";
    pub const CREATE:      &str = "calendar_department:create";
    pub const UPDATE:      &str = "calendar_department:update";
    pub const DELETE:      &str = "calendar_department:delete";
    pub const RESTORE:     &str = "calendar_department:restore";
    pub const TRASH:       &str = "calendar_department:trash";
    pub const EMPTY_TRASH: &str = "calendar_department:empty_trash";
    pub const BULK_CREATE: &str = "calendar_department:bulk_create";
    pub const UPSERT:      &str = "calendar_department:upsert";
}

/// Resource policy for CalendarDepartment — maps CRUD actions to permission strings.
pub struct CalendarDepartmentPolicy;

#[async_trait]
impl ResourcePolicy<CalendarDepartment> for CalendarDepartmentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarDepartment,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarDepartment handlers.
///
/// Wraps `CalendarDepartmentService` and checks `CalendarDepartmentPolicy` before delegating.
pub type CalendarDepartmentGuard = PermissionGuard<CalendarDepartment>;

/// Service-integrated permission guard for CalendarDepartment (for use in generated handlers).
pub type CalendarDepartmentServiceGuard = ServicePermissionGuard<CalendarDepartment, CalendarDepartmentService, CalendarDepartmentPolicy>;

// <<< CUSTOM
// END CUSTOM
