//! Auth configuration for Calendar handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Calendar>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarService;
use crate::domain::entity::Calendar;

/// Permission string constants for Calendar operations.
pub mod permissions {
    pub const LIST:        &str = "calendar:list";
    pub const READ:        &str = "calendar:read";
    pub const CREATE:      &str = "calendar:create";
    pub const UPDATE:      &str = "calendar:update";
    pub const DELETE:      &str = "calendar:delete";
    pub const RESTORE:     &str = "calendar:restore";
    pub const TRASH:       &str = "calendar:trash";
    pub const EMPTY_TRASH: &str = "calendar:empty_trash";
    pub const BULK_CREATE: &str = "calendar:bulk_create";
    pub const UPSERT:      &str = "calendar:upsert";
}

/// Resource policy for Calendar — maps CRUD actions to permission strings.
pub struct CalendarPolicy;

#[async_trait]
impl ResourcePolicy<Calendar> for CalendarPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Calendar,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Calendar handlers.
///
/// Wraps `CalendarService` and checks `CalendarPolicy` before delegating.
pub type CalendarGuard = PermissionGuard<Calendar>;

/// Service-integrated permission guard for Calendar (for use in generated handlers).
pub type CalendarServiceGuard = ServicePermissionGuard<Calendar, CalendarService, CalendarPolicy>;

// <<< CUSTOM
// END CUSTOM
