//! Auth configuration for CalendarReligion handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarReligion>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarReligionService;
use crate::domain::entity::CalendarReligion;

/// Permission string constants for CalendarReligion operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_religion:list";
    pub const READ:        &str = "calendar_religion:read";
    pub const CREATE:      &str = "calendar_religion:create";
    pub const UPDATE:      &str = "calendar_religion:update";
    pub const DELETE:      &str = "calendar_religion:delete";
    pub const RESTORE:     &str = "calendar_religion:restore";
    pub const TRASH:       &str = "calendar_religion:trash";
    pub const EMPTY_TRASH: &str = "calendar_religion:empty_trash";
    pub const BULK_CREATE: &str = "calendar_religion:bulk_create";
    pub const UPSERT:      &str = "calendar_religion:upsert";
}

/// Resource policy for CalendarReligion — maps CRUD actions to permission strings.
pub struct CalendarReligionPolicy;

#[async_trait]
impl ResourcePolicy<CalendarReligion> for CalendarReligionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarReligion,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarReligion handlers.
///
/// Wraps `CalendarReligionService` and checks `CalendarReligionPolicy` before delegating.
pub type CalendarReligionGuard = PermissionGuard<CalendarReligion>;

/// Service-integrated permission guard for CalendarReligion (for use in generated handlers).
pub type CalendarReligionServiceGuard = ServicePermissionGuard<CalendarReligion, CalendarReligionService, CalendarReligionPolicy>;

// <<< CUSTOM
// END CUSTOM
