//! Auth configuration for CalendarLevel handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarLevel>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarLevelService;
use crate::domain::entity::CalendarLevel;

/// Permission string constants for CalendarLevel operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_level:list";
    pub const READ:        &str = "calendar_level:read";
    pub const CREATE:      &str = "calendar_level:create";
    pub const UPDATE:      &str = "calendar_level:update";
    pub const DELETE:      &str = "calendar_level:delete";
    pub const RESTORE:     &str = "calendar_level:restore";
    pub const TRASH:       &str = "calendar_level:trash";
    pub const EMPTY_TRASH: &str = "calendar_level:empty_trash";
    pub const BULK_CREATE: &str = "calendar_level:bulk_create";
    pub const UPSERT:      &str = "calendar_level:upsert";
}

/// Resource policy for CalendarLevel — maps CRUD actions to permission strings.
pub struct CalendarLevelPolicy;

#[async_trait]
impl ResourcePolicy<CalendarLevel> for CalendarLevelPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarLevel,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarLevel handlers.
///
/// Wraps `CalendarLevelService` and checks `CalendarLevelPolicy` before delegating.
pub type CalendarLevelGuard = PermissionGuard<CalendarLevel>;

/// Service-integrated permission guard for CalendarLevel (for use in generated handlers).
pub type CalendarLevelServiceGuard = ServicePermissionGuard<CalendarLevel, CalendarLevelService, CalendarLevelPolicy>;

// <<< CUSTOM
// END CUSTOM
