//! Auth configuration for CalendarPosition handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarPosition>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarPositionService;
use crate::domain::entity::CalendarPosition;

/// Permission string constants for CalendarPosition operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_position:list";
    pub const READ:        &str = "calendar_position:read";
    pub const CREATE:      &str = "calendar_position:create";
    pub const UPDATE:      &str = "calendar_position:update";
    pub const DELETE:      &str = "calendar_position:delete";
    pub const RESTORE:     &str = "calendar_position:restore";
    pub const TRASH:       &str = "calendar_position:trash";
    pub const EMPTY_TRASH: &str = "calendar_position:empty_trash";
    pub const BULK_CREATE: &str = "calendar_position:bulk_create";
    pub const UPSERT:      &str = "calendar_position:upsert";
}

/// Resource policy for CalendarPosition — maps CRUD actions to permission strings.
pub struct CalendarPositionPolicy;

#[async_trait]
impl ResourcePolicy<CalendarPosition> for CalendarPositionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarPosition,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarPosition handlers.
///
/// Wraps `CalendarPositionService` and checks `CalendarPositionPolicy` before delegating.
pub type CalendarPositionGuard = PermissionGuard<CalendarPosition>;

/// Service-integrated permission guard for CalendarPosition (for use in generated handlers).
pub type CalendarPositionServiceGuard = ServicePermissionGuard<CalendarPosition, CalendarPositionService, CalendarPositionPolicy>;

// <<< CUSTOM
// END CUSTOM
