//! Auth configuration for CalendarEmployeeStatus handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarEmployeeStatus>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarEmployeeStatusService;
use crate::domain::entity::CalendarEmployeeStatus;

/// Permission string constants for CalendarEmployeeStatus operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_employee_status:list";
    pub const READ:        &str = "calendar_employee_status:read";
    pub const CREATE:      &str = "calendar_employee_status:create";
    pub const UPDATE:      &str = "calendar_employee_status:update";
    pub const DELETE:      &str = "calendar_employee_status:delete";
    pub const RESTORE:     &str = "calendar_employee_status:restore";
    pub const TRASH:       &str = "calendar_employee_status:trash";
    pub const EMPTY_TRASH: &str = "calendar_employee_status:empty_trash";
    pub const BULK_CREATE: &str = "calendar_employee_status:bulk_create";
    pub const UPSERT:      &str = "calendar_employee_status:upsert";
}

/// Resource policy for CalendarEmployeeStatus — maps CRUD actions to permission strings.
pub struct CalendarEmployeeStatusPolicy;

#[async_trait]
impl ResourcePolicy<CalendarEmployeeStatus> for CalendarEmployeeStatusPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarEmployeeStatus,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarEmployeeStatus handlers.
///
/// Wraps `CalendarEmployeeStatusService` and checks `CalendarEmployeeStatusPolicy` before delegating.
pub type CalendarEmployeeStatusGuard = PermissionGuard<CalendarEmployeeStatus>;

/// Service-integrated permission guard for CalendarEmployeeStatus (for use in generated handlers).
pub type CalendarEmployeeStatusServiceGuard = ServicePermissionGuard<CalendarEmployeeStatus, CalendarEmployeeStatusService, CalendarEmployeeStatusPolicy>;

// <<< CUSTOM
// END CUSTOM
