//! Auth configuration for CalendarEmployee handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarEmployee>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarEmployeeService;
use crate::domain::entity::CalendarEmployee;

/// Permission string constants for CalendarEmployee operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_employee:list";
    pub const READ:        &str = "calendar_employee:read";
    pub const CREATE:      &str = "calendar_employee:create";
    pub const UPDATE:      &str = "calendar_employee:update";
    pub const DELETE:      &str = "calendar_employee:delete";
    pub const RESTORE:     &str = "calendar_employee:restore";
    pub const TRASH:       &str = "calendar_employee:trash";
    pub const EMPTY_TRASH: &str = "calendar_employee:empty_trash";
    pub const BULK_CREATE: &str = "calendar_employee:bulk_create";
    pub const UPSERT:      &str = "calendar_employee:upsert";
}

/// Resource policy for CalendarEmployee — maps CRUD actions to permission strings.
pub struct CalendarEmployeePolicy;

#[async_trait]
impl ResourcePolicy<CalendarEmployee> for CalendarEmployeePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarEmployee,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarEmployee handlers.
///
/// Wraps `CalendarEmployeeService` and checks `CalendarEmployeePolicy` before delegating.
pub type CalendarEmployeeGuard = PermissionGuard<CalendarEmployee>;

/// Service-integrated permission guard for CalendarEmployee (for use in generated handlers).
pub type CalendarEmployeeServiceGuard = ServicePermissionGuard<CalendarEmployee, CalendarEmployeeService, CalendarEmployeePolicy>;

// <<< CUSTOM
// END CUSTOM
