//! Auth configuration for CalendarBranch handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CalendarBranch>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CalendarBranchService;
use crate::domain::entity::CalendarBranch;

/// Permission string constants for CalendarBranch operations.
pub mod permissions {
    pub const LIST:        &str = "calendar_branch:list";
    pub const READ:        &str = "calendar_branch:read";
    pub const CREATE:      &str = "calendar_branch:create";
    pub const UPDATE:      &str = "calendar_branch:update";
    pub const DELETE:      &str = "calendar_branch:delete";
    pub const RESTORE:     &str = "calendar_branch:restore";
    pub const TRASH:       &str = "calendar_branch:trash";
    pub const EMPTY_TRASH: &str = "calendar_branch:empty_trash";
    pub const BULK_CREATE: &str = "calendar_branch:bulk_create";
    pub const UPSERT:      &str = "calendar_branch:upsert";
}

/// Resource policy for CalendarBranch — maps CRUD actions to permission strings.
pub struct CalendarBranchPolicy;

#[async_trait]
impl ResourcePolicy<CalendarBranch> for CalendarBranchPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CalendarBranch,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CalendarBranch handlers.
///
/// Wraps `CalendarBranchService` and checks `CalendarBranchPolicy` before delegating.
pub type CalendarBranchGuard = PermissionGuard<CalendarBranch>;

/// Service-integrated permission guard for CalendarBranch (for use in generated handlers).
pub type CalendarBranchServiceGuard = ServicePermissionGuard<CalendarBranch, CalendarBranchService, CalendarBranchPolicy>;

// <<< CUSTOM
// END CUSTOM
