//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod calendar_auth;
pub mod calendar_branch_auth;
pub mod calendar_department_auth;
pub mod calendar_employee_auth;
pub mod calendar_employee_status_auth;
pub mod calendar_level_auth;
pub mod calendar_position_auth;
pub mod calendar_religion_auth;

pub use calendar_auth::{CalendarPolicy, CalendarGuard, CalendarServiceGuard};
pub use calendar_branch_auth::{CalendarBranchPolicy, CalendarBranchGuard, CalendarBranchServiceGuard};
pub use calendar_department_auth::{CalendarDepartmentPolicy, CalendarDepartmentGuard, CalendarDepartmentServiceGuard};
pub use calendar_employee_auth::{CalendarEmployeePolicy, CalendarEmployeeGuard, CalendarEmployeeServiceGuard};
pub use calendar_employee_status_auth::{CalendarEmployeeStatusPolicy, CalendarEmployeeStatusGuard, CalendarEmployeeStatusServiceGuard};
pub use calendar_level_auth::{CalendarLevelPolicy, CalendarLevelGuard, CalendarLevelServiceGuard};
pub use calendar_position_auth::{CalendarPositionPolicy, CalendarPositionGuard, CalendarPositionServiceGuard};
pub use calendar_religion_auth::{CalendarReligionPolicy, CalendarReligionGuard, CalendarReligionServiceGuard};

// <<< CUSTOM
// END CUSTOM
