//! CalendarLevel API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CalendarLevel CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALENDARLEVEL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CalendarLevel
pub struct CalendarLevelTestData;

impl TestDataGenerator for CalendarLevelTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "calendar_id": Uuid::new_v4().to_string(),
            "level_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "calendar_id": Uuid::new_v4().to_string(),
            "level_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/calendars", &super::calendar_api_test::CalendarTestData).await {
            deps.push(("calendar_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// CALENDARLEVEL API TEST
// ============================================================================

/// CalendarLevel API test suite
pub struct CalendarLevelApiTest {
    inner: GenericCrudTest<CalendarLevelTestData>,
}

impl CalendarLevelApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/calendar_levels", "CalendarLevel");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CalendarLevelTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CalendarLevelApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_calendar_level_crud() {
        let mut test = CalendarLevelApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CalendarLevel specific tests here
// <<< CUSTOM TESTS END >>>
