//! CalendarEventException API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CalendarEventException CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALENDAREVENTEXCEPTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CalendarEventException
pub struct CalendarEventExceptionTestData;

impl TestDataGenerator for CalendarEventExceptionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "series_id": Uuid::new_v4().to_string(),
            "event_id": Uuid::new_v4().to_string(),
            "slot_start_at": now,
            "slot_stop_at": now,
            "kind": "edited",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "series_id": Uuid::new_v4().to_string(),
            "event_id": Uuid::new_v4().to_string(),
            "slot_start_at": now,
            "slot_stop_at": now,
            "kind": "edited",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/event_series", &super::calendar_event_series_api_test::CalendarEventSeriesTestData).await {
            deps.push(("series_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/events", &super::calendar_event_api_test::CalendarEventTestData).await {
            deps.push(("event_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// CALENDAREVENTEXCEPTION API TEST
// ============================================================================

/// CalendarEventException API test suite
pub struct CalendarEventExceptionApiTest {
    inner: GenericCrudTest<CalendarEventExceptionTestData>,
}

impl CalendarEventExceptionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/event_exceptions", "CalendarEventException");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CalendarEventExceptionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CalendarEventExceptionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_calendar_event_exception_crud() {
        let mut test = CalendarEventExceptionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CalendarEventException specific tests here
// <<< CUSTOM TESTS END >>>
