//! Calendar API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Calendar CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALENDAR TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Calendar
pub struct CalendarTestData;

impl TestDataGenerator for CalendarTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "date_start": Utc::now().format("%Y-%m-%d").to_string(),
            "date_end": Utc::now().format("%Y-%m-%d").to_string(),
            "is_holiday": false,
            "can_everyone_view": false,
            "note": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "date_start": Utc::now().format("%Y-%m-%d").to_string(),
            "date_end": Utc::now().format("%Y-%m-%d").to_string(),
            "is_holiday": false,
            "can_everyone_view": false,
            "note": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CALENDAR API TEST
// ============================================================================

/// Calendar API test suite
pub struct CalendarApiTest {
    inner: GenericCrudTest<CalendarTestData>,
}

impl CalendarApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/calendars", "Calendar");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CalendarTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CalendarApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_calendar_crud() {
        let mut test = CalendarApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Calendar specific tests here
// <<< CUSTOM TESTS END >>>
