//! CalendarEventSeries API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CalendarEventSeries CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALENDAREVENTSERIES TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CalendarEventSeries
pub struct CalendarEventSeriesTestData;

impl TestDataGenerator for CalendarEventSeriesTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": null,
            "freq": "daily",
            "interval": 1,
            "by_weekday": null,
            "by_monthday": null,
            "until": null,
            "count": null,
            "base_event_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": null,
            "freq": "daily",
            "interval": 1,
            "by_weekday": null,
            "by_monthday": null,
            "until": null,
            "count": null,
            "base_event_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/events", &super::calendar_event_api_test::CalendarEventTestData).await {
            deps.push(("base_event_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// CALENDAREVENTSERIES API TEST
// ============================================================================

/// CalendarEventSeries API test suite
pub struct CalendarEventSeriesApiTest {
    inner: GenericCrudTest<CalendarEventSeriesTestData>,
}

impl CalendarEventSeriesApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/event_series", "CalendarEventSeries");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CalendarEventSeriesTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CalendarEventSeriesApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_calendar_event_series_crud() {
        let mut test = CalendarEventSeriesApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CalendarEventSeries specific tests here
// <<< CUSTOM TESTS END >>>
