//! CalendarEvent API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CalendarEvent CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALENDAREVENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CalendarEvent
pub struct CalendarEventTestData;

impl TestDataGenerator for CalendarEventTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "series_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "start_at": now,
            "stop_at": now,
            "privacy": "public",
            "organizer_user_id": Uuid::new_v4().to_string(),
            "location": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "series_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "start_at": now,
            "stop_at": now,
            "privacy": "public",
            "organizer_user_id": Uuid::new_v4().to_string(),
            "location": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CALENDAREVENT API TEST
// ============================================================================

/// CalendarEvent API test suite
pub struct CalendarEventApiTest {
    inner: GenericCrudTest<CalendarEventTestData>,
}

impl CalendarEventApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/events", "CalendarEvent");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CalendarEventTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CalendarEventApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_calendar_event_crud() {
        let mut test = CalendarEventApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CalendarEvent specific tests here
// <<< CUSTOM TESTS END >>>
