//! Calendar Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CalendarService;
use crate::application::service::CalendarBranchService;
use crate::application::service::CalendarDepartmentService;
use crate::application::service::CalendarEmployeeService;
use crate::application::service::CalendarEmployeeStatusService;
use crate::application::service::CalendarLevelService;
use crate::application::service::CalendarPositionService;
use crate::application::service::CalendarReligionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Calendar service
    pub calendar_service: Arc<CalendarService>,
    /// CalendarBranch service
    pub calendar_branch_service: Arc<CalendarBranchService>,
    /// CalendarDepartment service
    pub calendar_department_service: Arc<CalendarDepartmentService>,
    /// CalendarEmployee service
    pub calendar_employee_service: Arc<CalendarEmployeeService>,
    /// CalendarEmployeeStatus service
    pub calendar_employee_status_service: Arc<CalendarEmployeeStatusService>,
    /// CalendarLevel service
    pub calendar_level_service: Arc<CalendarLevelService>,
    /// CalendarPosition service
    pub calendar_position_service: Arc<CalendarPositionService>,
    /// CalendarReligion service
    pub calendar_religion_service: Arc<CalendarReligionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        calendar_service: Arc<CalendarService>,
        calendar_branch_service: Arc<CalendarBranchService>,
        calendar_department_service: Arc<CalendarDepartmentService>,
        calendar_employee_service: Arc<CalendarEmployeeService>,
        calendar_employee_status_service: Arc<CalendarEmployeeStatusService>,
        calendar_level_service: Arc<CalendarLevelService>,
        calendar_position_service: Arc<CalendarPositionService>,
        calendar_religion_service: Arc<CalendarReligionService>
    ) -> Self {
        Self {
            calendar_service,
            calendar_branch_service,
            calendar_department_service,
            calendar_employee_service,
            calendar_employee_status_service,
            calendar_level_service,
            calendar_position_service,
            calendar_religion_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::CalendarModule) -> Self {
        Self {
            calendar_service: module.calendar_service.clone(),
            calendar_branch_service: module.calendar_branch_service.clone(),
            calendar_department_service: module.calendar_department_service.clone(),
            calendar_employee_service: module.calendar_employee_service.clone(),
            calendar_employee_status_service: module.calendar_employee_status_service.clone(),
            calendar_level_service: module.calendar_level_service.clone(),
            calendar_position_service: module.calendar_position_service.clone(),
            calendar_religion_service: module.calendar_religion_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    calendar_service: Option<Arc<CalendarService>>,
    calendar_branch_service: Option<Arc<CalendarBranchService>>,
    calendar_department_service: Option<Arc<CalendarDepartmentService>>,
    calendar_employee_service: Option<Arc<CalendarEmployeeService>>,
    calendar_employee_status_service: Option<Arc<CalendarEmployeeStatusService>>,
    calendar_level_service: Option<Arc<CalendarLevelService>>,
    calendar_position_service: Option<Arc<CalendarPositionService>>,
    calendar_religion_service: Option<Arc<CalendarReligionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Calendar service.
    pub fn with_calendar_service(mut self, service: Arc<CalendarService>) -> Self {
        self.calendar_service = Some(service);
        self
    }

    /// Set the CalendarBranch service.
    pub fn with_calendar_branch_service(mut self, service: Arc<CalendarBranchService>) -> Self {
        self.calendar_branch_service = Some(service);
        self
    }

    /// Set the CalendarDepartment service.
    pub fn with_calendar_department_service(mut self, service: Arc<CalendarDepartmentService>) -> Self {
        self.calendar_department_service = Some(service);
        self
    }

    /// Set the CalendarEmployee service.
    pub fn with_calendar_employee_service(mut self, service: Arc<CalendarEmployeeService>) -> Self {
        self.calendar_employee_service = Some(service);
        self
    }

    /// Set the CalendarEmployeeStatus service.
    pub fn with_calendar_employee_status_service(mut self, service: Arc<CalendarEmployeeStatusService>) -> Self {
        self.calendar_employee_status_service = Some(service);
        self
    }

    /// Set the CalendarLevel service.
    pub fn with_calendar_level_service(mut self, service: Arc<CalendarLevelService>) -> Self {
        self.calendar_level_service = Some(service);
        self
    }

    /// Set the CalendarPosition service.
    pub fn with_calendar_position_service(mut self, service: Arc<CalendarPositionService>) -> Self {
        self.calendar_position_service = Some(service);
        self
    }

    /// Set the CalendarReligion service.
    pub fn with_calendar_religion_service(mut self, service: Arc<CalendarReligionService>) -> Self {
        self.calendar_religion_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            calendar_service: self.calendar_service.expect("calendar_service is required"),
            calendar_branch_service: self.calendar_branch_service.expect("calendar_branch_service is required"),
            calendar_department_service: self.calendar_department_service.expect("calendar_department_service is required"),
            calendar_employee_service: self.calendar_employee_service.expect("calendar_employee_service is required"),
            calendar_employee_status_service: self.calendar_employee_status_service.expect("calendar_employee_status_service is required"),
            calendar_level_service: self.calendar_level_service.expect("calendar_level_service is required"),
            calendar_position_service: self.calendar_position_service.expect("calendar_position_service is required"),
            calendar_religion_service: self.calendar_religion_service.expect("calendar_religion_service is required"),
        }
    }
}
