//! Public events for Calendar module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CALENDAR EVENTS
// ============================================================================

/// Event published when a Calendar is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarCreatedEvent {
    pub id: CalendarId,
    pub data: CalendarDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Calendar is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarUpdatedEvent {
    pub id: CalendarId,
    pub data: CalendarDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Calendar is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDeletedEvent {
    pub id: CalendarId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDARBRANCH EVENTS
// ============================================================================

/// Event published when a CalendarBranch is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchCreatedEvent {
    pub id: CalendarBranchId,
    pub data: CalendarBranchDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarBranch is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchUpdatedEvent {
    pub id: CalendarBranchId,
    pub data: CalendarBranchDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarBranch is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchDeletedEvent {
    pub id: CalendarBranchId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDARDEPARTMENT EVENTS
// ============================================================================

/// Event published when a CalendarDepartment is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentCreatedEvent {
    pub id: CalendarDepartmentId,
    pub data: CalendarDepartmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarDepartment is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentUpdatedEvent {
    pub id: CalendarDepartmentId,
    pub data: CalendarDepartmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarDepartment is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentDeletedEvent {
    pub id: CalendarDepartmentId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDAREMPLOYEE EVENTS
// ============================================================================

/// Event published when a CalendarEmployee is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeCreatedEvent {
    pub id: CalendarEmployeeId,
    pub data: CalendarEmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarEmployee is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeUpdatedEvent {
    pub id: CalendarEmployeeId,
    pub data: CalendarEmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarEmployee is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeDeletedEvent {
    pub id: CalendarEmployeeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDAREMPLOYEESTATUS EVENTS
// ============================================================================

/// Event published when a CalendarEmployeeStatus is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusCreatedEvent {
    pub id: CalendarEmployeeStatusId,
    pub data: CalendarEmployeeStatusDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarEmployeeStatus is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusUpdatedEvent {
    pub id: CalendarEmployeeStatusId,
    pub data: CalendarEmployeeStatusDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarEmployeeStatus is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusDeletedEvent {
    pub id: CalendarEmployeeStatusId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDARLEVEL EVENTS
// ============================================================================

/// Event published when a CalendarLevel is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelCreatedEvent {
    pub id: CalendarLevelId,
    pub data: CalendarLevelDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarLevel is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelUpdatedEvent {
    pub id: CalendarLevelId,
    pub data: CalendarLevelDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarLevel is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelDeletedEvent {
    pub id: CalendarLevelId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDARPOSITION EVENTS
// ============================================================================

/// Event published when a CalendarPosition is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionCreatedEvent {
    pub id: CalendarPositionId,
    pub data: CalendarPositionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarPosition is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionUpdatedEvent {
    pub id: CalendarPositionId,
    pub data: CalendarPositionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarPosition is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionDeletedEvent {
    pub id: CalendarPositionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CALENDARRELIGION EVENTS
// ============================================================================

/// Event published when a CalendarReligion is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionCreatedEvent {
    pub id: CalendarReligionId,
    pub data: CalendarReligionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarReligion is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionUpdatedEvent {
    pub id: CalendarReligionId,
    pub data: CalendarReligionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CalendarReligion is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionDeletedEvent {
    pub id: CalendarReligionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Calendar module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CalendarEvent {
    CalendarCreated(CalendarCreatedEvent),
    CalendarUpdated(CalendarUpdatedEvent),
    CalendarDeleted(CalendarDeletedEvent),
    CalendarBranchCreated(CalendarBranchCreatedEvent),
    CalendarBranchUpdated(CalendarBranchUpdatedEvent),
    CalendarBranchDeleted(CalendarBranchDeletedEvent),
    CalendarDepartmentCreated(CalendarDepartmentCreatedEvent),
    CalendarDepartmentUpdated(CalendarDepartmentUpdatedEvent),
    CalendarDepartmentDeleted(CalendarDepartmentDeletedEvent),
    CalendarEmployeeCreated(CalendarEmployeeCreatedEvent),
    CalendarEmployeeUpdated(CalendarEmployeeUpdatedEvent),
    CalendarEmployeeDeleted(CalendarEmployeeDeletedEvent),
    CalendarEmployeeStatusCreated(CalendarEmployeeStatusCreatedEvent),
    CalendarEmployeeStatusUpdated(CalendarEmployeeStatusUpdatedEvent),
    CalendarEmployeeStatusDeleted(CalendarEmployeeStatusDeletedEvent),
    CalendarLevelCreated(CalendarLevelCreatedEvent),
    CalendarLevelUpdated(CalendarLevelUpdatedEvent),
    CalendarLevelDeleted(CalendarLevelDeletedEvent),
    CalendarPositionCreated(CalendarPositionCreatedEvent),
    CalendarPositionUpdated(CalendarPositionUpdatedEvent),
    CalendarPositionDeleted(CalendarPositionDeletedEvent),
    CalendarReligionCreated(CalendarReligionCreatedEvent),
    CalendarReligionUpdated(CalendarReligionUpdatedEvent),
    CalendarReligionDeleted(CalendarReligionDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for CalendarEventMetadata {
    fn default() -> Self {
        Self {
            module: "calendar",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
