//! Calendar Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Calendar exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use calendar::exports::{CalendarDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CalendarDto` - Data transfer object for Calendar
/// - `CalendarSummary` - Summary view of Calendar
/// - `CalendarId` - Type-safe ID wrapper
/// - `CalendarBranchDto` - Data transfer object for CalendarBranch
/// - `CalendarBranchSummary` - Summary view of CalendarBranch
/// - `CalendarBranchId` - Type-safe ID wrapper
/// - `CalendarDepartmentDto` - Data transfer object for CalendarDepartment
/// - `CalendarDepartmentSummary` - Summary view of CalendarDepartment
/// - `CalendarDepartmentId` - Type-safe ID wrapper
/// - `CalendarEmployeeDto` - Data transfer object for CalendarEmployee
/// - `CalendarEmployeeSummary` - Summary view of CalendarEmployee
/// - `CalendarEmployeeId` - Type-safe ID wrapper
/// - `CalendarEmployeeStatusDto` - Data transfer object for CalendarEmployeeStatus
/// - `CalendarEmployeeStatusSummary` - Summary view of CalendarEmployeeStatus
/// - `CalendarEmployeeStatusId` - Type-safe ID wrapper
/// - `CalendarEventDto` - Data transfer object for CalendarEvent
/// - `CalendarEventSummary` - Summary view of CalendarEvent
/// - `CalendarEventId` - Type-safe ID wrapper
/// - `CalendarEventAttendeeDto` - Data transfer object for CalendarEventAttendee
/// - `CalendarEventAttendeeSummary` - Summary view of CalendarEventAttendee
/// - `CalendarEventAttendeeId` - Type-safe ID wrapper
/// - `CalendarEventExceptionDto` - Data transfer object for CalendarEventException
/// - `CalendarEventExceptionSummary` - Summary view of CalendarEventException
/// - `CalendarEventExceptionId` - Type-safe ID wrapper
/// - `CalendarEventSeriesDto` - Data transfer object for CalendarEventSeries
/// - `CalendarEventSeriesSummary` - Summary view of CalendarEventSeries
/// - `CalendarEventSeriesId` - Type-safe ID wrapper
/// - `CalendarLevelDto` - Data transfer object for CalendarLevel
/// - `CalendarLevelSummary` - Summary view of CalendarLevel
/// - `CalendarLevelId` - Type-safe ID wrapper
/// - `CalendarPositionDto` - Data transfer object for CalendarPosition
/// - `CalendarPositionSummary` - Summary view of CalendarPosition
/// - `CalendarPositionId` - Type-safe ID wrapper
/// - `CalendarReligionDto` - Data transfer object for CalendarReligion
/// - `CalendarReligionSummary` - Summary view of CalendarReligion
/// - `CalendarReligionId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `CalendarCreatedEvent` - Published when Calendar is created
/// - `CalendarUpdatedEvent` - Published when Calendar is updated
/// - `CalendarDeletedEvent` - Published when Calendar is deleted
/// - `CalendarBranchCreatedEvent` - Published when CalendarBranch is created
/// - `CalendarBranchUpdatedEvent` - Published when CalendarBranch is updated
/// - `CalendarBranchDeletedEvent` - Published when CalendarBranch is deleted
/// - `CalendarDepartmentCreatedEvent` - Published when CalendarDepartment is created
/// - `CalendarDepartmentUpdatedEvent` - Published when CalendarDepartment is updated
/// - `CalendarDepartmentDeletedEvent` - Published when CalendarDepartment is deleted
/// - `CalendarEmployeeCreatedEvent` - Published when CalendarEmployee is created
/// - `CalendarEmployeeUpdatedEvent` - Published when CalendarEmployee is updated
/// - `CalendarEmployeeDeletedEvent` - Published when CalendarEmployee is deleted
/// - `CalendarEmployeeStatusCreatedEvent` - Published when CalendarEmployeeStatus is created
/// - `CalendarEmployeeStatusUpdatedEvent` - Published when CalendarEmployeeStatus is updated
/// - `CalendarEmployeeStatusDeletedEvent` - Published when CalendarEmployeeStatus is deleted
/// - `CalendarEventCreatedEvent` - Published when CalendarEvent is created
/// - `CalendarEventUpdatedEvent` - Published when CalendarEvent is updated
/// - `CalendarEventDeletedEvent` - Published when CalendarEvent is deleted
/// - `CalendarEventAttendeeCreatedEvent` - Published when CalendarEventAttendee is created
/// - `CalendarEventAttendeeUpdatedEvent` - Published when CalendarEventAttendee is updated
/// - `CalendarEventAttendeeDeletedEvent` - Published when CalendarEventAttendee is deleted
/// - `CalendarEventExceptionCreatedEvent` - Published when CalendarEventException is created
/// - `CalendarEventExceptionUpdatedEvent` - Published when CalendarEventException is updated
/// - `CalendarEventExceptionDeletedEvent` - Published when CalendarEventException is deleted
/// - `CalendarEventSeriesCreatedEvent` - Published when CalendarEventSeries is created
/// - `CalendarEventSeriesUpdatedEvent` - Published when CalendarEventSeries is updated
/// - `CalendarEventSeriesDeletedEvent` - Published when CalendarEventSeries is deleted
/// - `CalendarLevelCreatedEvent` - Published when CalendarLevel is created
/// - `CalendarLevelUpdatedEvent` - Published when CalendarLevel is updated
/// - `CalendarLevelDeletedEvent` - Published when CalendarLevel is deleted
/// - `CalendarPositionCreatedEvent` - Published when CalendarPosition is created
/// - `CalendarPositionUpdatedEvent` - Published when CalendarPosition is updated
/// - `CalendarPositionDeletedEvent` - Published when CalendarPosition is deleted
/// - `CalendarReligionCreatedEvent` - Published when CalendarReligion is created
/// - `CalendarReligionUpdatedEvent` - Published when CalendarReligion is updated
/// - `CalendarReligionDeletedEvent` - Published when CalendarReligion is deleted
pub struct ExportSummary;
