//! Public types for Calendar module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use crate::domain::entity::*;

// ============================================================================
// CALENDAR TYPES
// ============================================================================

/// Type-safe ID for Calendar
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarId(pub Uuid);

impl CalendarId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarId> for Uuid {
    fn from(id: CalendarId) -> Self {
        id.0
    }
}

/// Data transfer object for Calendar
///
/// This is the public representation of Calendar for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDto {
    pub id: CalendarId,
    pub company_id: Uuid,
    pub name: String,
    pub date_start: NaiveDate,
    pub date_end: NaiveDate,
    pub is_holiday: bool,
    pub can_everyone_view: bool,
    pub note: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Calendar for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarSummary {
    pub id: CalendarId,
    pub name: String,
}

/// Reference to Calendar for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarRef {
    pub id: CalendarId,
}

// ============================================================================
// CALENDARBRANCH TYPES
// ============================================================================

/// Type-safe ID for CalendarBranch
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarBranchId(pub Uuid);

impl CalendarBranchId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarBranchId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarBranchId> for Uuid {
    fn from(id: CalendarBranchId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarBranch
///
/// This is the public representation of CalendarBranch for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchDto {
    pub id: CalendarBranchId,
    pub calendar_id: Uuid,
    pub company_id: Uuid,
    pub branch_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarBranch for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchSummary {
    pub id: CalendarBranchId,
}

/// Reference to CalendarBranch for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarBranchRef {
    pub id: CalendarBranchId,
}

// ============================================================================
// CALENDARDEPARTMENT TYPES
// ============================================================================

/// Type-safe ID for CalendarDepartment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarDepartmentId(pub Uuid);

impl CalendarDepartmentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarDepartmentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarDepartmentId> for Uuid {
    fn from(id: CalendarDepartmentId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarDepartment
///
/// This is the public representation of CalendarDepartment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentDto {
    pub id: CalendarDepartmentId,
    pub calendar_id: Uuid,
    pub department_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarDepartment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentSummary {
    pub id: CalendarDepartmentId,
}

/// Reference to CalendarDepartment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDepartmentRef {
    pub id: CalendarDepartmentId,
}

// ============================================================================
// CALENDAREMPLOYEE TYPES
// ============================================================================

/// Type-safe ID for CalendarEmployee
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEmployeeId(pub Uuid);

impl CalendarEmployeeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEmployeeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEmployeeId> for Uuid {
    fn from(id: CalendarEmployeeId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEmployee
///
/// This is the public representation of CalendarEmployee for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeDto {
    pub id: CalendarEmployeeId,
    pub calendar_id: Uuid,
    pub employee_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEmployee for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeSummary {
    pub id: CalendarEmployeeId,
}

/// Reference to CalendarEmployee for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeRef {
    pub id: CalendarEmployeeId,
}

// ============================================================================
// CALENDAREMPLOYEESTATUS TYPES
// ============================================================================

/// Type-safe ID for CalendarEmployeeStatus
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusId(pub Uuid);

impl CalendarEmployeeStatusId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEmployeeStatusId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEmployeeStatusId> for Uuid {
    fn from(id: CalendarEmployeeStatusId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEmployeeStatus
///
/// This is the public representation of CalendarEmployeeStatus for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusDto {
    pub id: CalendarEmployeeStatusId,
    pub calendar_id: Uuid,
    pub employment_status: EmploymentStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEmployeeStatus for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusSummary {
    pub id: CalendarEmployeeStatusId,
}

/// Reference to CalendarEmployeeStatus for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEmployeeStatusRef {
    pub id: CalendarEmployeeStatusId,
}

// ============================================================================
// CALENDAREVENT TYPES
// ============================================================================

/// Type-safe ID for CalendarEvent
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEventId(pub Uuid);

impl CalendarEventId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEventId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEventId> for Uuid {
    fn from(id: CalendarEventId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEvent
///
/// This is the public representation of CalendarEvent for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventDto {
    pub id: CalendarEventId,
    pub company_id: Uuid,
    pub series_id: Option<Uuid>,
    pub title: String,
    pub description: Option<String>,
    pub start_at: DateTime<Utc>,
    pub stop_at: DateTime<Utc>,
    pub privacy: EventPrivacy,
    pub organizer_user_id: Uuid,
    pub location: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEvent for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventSummary {
    pub id: CalendarEventId,
    pub title: String,
}

/// Reference to CalendarEvent for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventRef {
    pub id: CalendarEventId,
}

// ============================================================================
// CALENDAREVENTATTENDEE TYPES
// ============================================================================

/// Type-safe ID for CalendarEventAttendee
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEventAttendeeId(pub Uuid);

impl CalendarEventAttendeeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEventAttendeeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEventAttendeeId> for Uuid {
    fn from(id: CalendarEventAttendeeId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEventAttendee
///
/// This is the public representation of CalendarEventAttendee for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventAttendeeDto {
    pub id: CalendarEventAttendeeId,
    pub company_id: Uuid,
    pub event_id: Uuid,
    pub user_id: Uuid,
    pub state: EventAttendeeState,
    pub access_token: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEventAttendee for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventAttendeeSummary {
    pub id: CalendarEventAttendeeId,
}

/// Reference to CalendarEventAttendee for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventAttendeeRef {
    pub id: CalendarEventAttendeeId,
}

// ============================================================================
// CALENDAREVENTEXCEPTION TYPES
// ============================================================================

/// Type-safe ID for CalendarEventException
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEventExceptionId(pub Uuid);

impl CalendarEventExceptionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEventExceptionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEventExceptionId> for Uuid {
    fn from(id: CalendarEventExceptionId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEventException
///
/// This is the public representation of CalendarEventException for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventExceptionDto {
    pub id: CalendarEventExceptionId,
    pub company_id: Uuid,
    pub series_id: Uuid,
    pub event_id: Uuid,
    pub slot_start_at: DateTime<Utc>,
    pub slot_stop_at: DateTime<Utc>,
    pub kind: EventExceptionKind,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEventException for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventExceptionSummary {
    pub id: CalendarEventExceptionId,
}

/// Reference to CalendarEventException for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventExceptionRef {
    pub id: CalendarEventExceptionId,
}

// ============================================================================
// CALENDAREVENTSERIES TYPES
// ============================================================================

/// Type-safe ID for CalendarEventSeries
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarEventSeriesId(pub Uuid);

impl CalendarEventSeriesId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarEventSeriesId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarEventSeriesId> for Uuid {
    fn from(id: CalendarEventSeriesId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarEventSeries
///
/// This is the public representation of CalendarEventSeries for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventSeriesDto {
    pub id: CalendarEventSeriesId,
    pub company_id: Uuid,
    pub name: Option<String>,
    pub freq: EventRecurrenceFreq,
    pub interval: i32,
    pub by_weekday: Option<String>,
    pub by_monthday: Option<String>,
    pub until: Option<NaiveDate>,
    pub count: Option<i32>,
    pub base_event_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarEventSeries for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventSeriesSummary {
    pub id: CalendarEventSeriesId,
    pub name: Option<String>,
}

/// Reference to CalendarEventSeries for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarEventSeriesRef {
    pub id: CalendarEventSeriesId,
}

// ============================================================================
// CALENDARLEVEL TYPES
// ============================================================================

/// Type-safe ID for CalendarLevel
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarLevelId(pub Uuid);

impl CalendarLevelId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarLevelId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarLevelId> for Uuid {
    fn from(id: CalendarLevelId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarLevel
///
/// This is the public representation of CalendarLevel for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelDto {
    pub id: CalendarLevelId,
    pub calendar_id: Uuid,
    pub level_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarLevel for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelSummary {
    pub id: CalendarLevelId,
}

/// Reference to CalendarLevel for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarLevelRef {
    pub id: CalendarLevelId,
}

// ============================================================================
// CALENDARPOSITION TYPES
// ============================================================================

/// Type-safe ID for CalendarPosition
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarPositionId(pub Uuid);

impl CalendarPositionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarPositionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarPositionId> for Uuid {
    fn from(id: CalendarPositionId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarPosition
///
/// This is the public representation of CalendarPosition for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionDto {
    pub id: CalendarPositionId,
    pub calendar_id: Uuid,
    pub position_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarPosition for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionSummary {
    pub id: CalendarPositionId,
}

/// Reference to CalendarPosition for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarPositionRef {
    pub id: CalendarPositionId,
}

// ============================================================================
// CALENDARRELIGION TYPES
// ============================================================================

/// Type-safe ID for CalendarReligion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CalendarReligionId(pub Uuid);

impl CalendarReligionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CalendarReligionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CalendarReligionId> for Uuid {
    fn from(id: CalendarReligionId) -> Self {
        id.0
    }
}

/// Data transfer object for CalendarReligion
///
/// This is the public representation of CalendarReligion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionDto {
    pub id: CalendarReligionId,
    pub calendar_id: Uuid,
    pub religion_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of CalendarReligion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionSummary {
    pub id: CalendarReligionId,
}

/// Reference to CalendarReligion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarReligionRef {
    pub id: CalendarReligionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
