//! Application layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - Commands (CQRS write operations)
//! - Queries (CQRS read operations)
//! - Services (business logic)
//! - Middleware (Auth & RBAC)
//! - Triggers (lifecycle hooks)
//! - Validation (input validation)
//! - Workflows (saga/orchestration patterns)

pub mod service;
pub mod validator;
pub mod workflows;

// Re-exports
pub use service::*;
// <<< CUSTOM
// The permission-vocabulary layer (application/auth/*): hand-written files
// in the generated shape, user-owned per metaphor.codegen.yaml. The
// declaration lives in the custom block so regeneration keeps it.
pub mod auth;
// END CUSTOM
