//! Calendar Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CalendarService;
pub use application::service::CalendarBranchService;
pub use application::service::CalendarDepartmentService;
pub use application::service::CalendarEmployeeService;
pub use application::service::CalendarEmployeeStatusService;
pub use application::service::CalendarLevelService;
pub use application::service::CalendarPositionService;
pub use application::service::CalendarReligionService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Calendar module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let calendar = CalendarModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = calendar.all_crud_routes();
/// ```
pub struct CalendarModule {
    pub(crate) calendar_service: Arc<CalendarService>,
    pub(crate) calendar_branch_service: Arc<CalendarBranchService>,
    pub(crate) calendar_department_service: Arc<CalendarDepartmentService>,
    pub(crate) calendar_employee_service: Arc<CalendarEmployeeService>,
    pub(crate) calendar_employee_status_service: Arc<CalendarEmployeeStatusService>,
    pub(crate) calendar_level_service: Arc<CalendarLevelService>,
    pub(crate) calendar_position_service: Arc<CalendarPositionService>,
    pub(crate) calendar_religion_service: Arc<CalendarReligionService>,
    // <<< CUSTOM FIELDS
    // Held so the `CalendarQueryService` impl can delegate `working_days` to the repo's
    // hand-written SQL, and standard lookups to the CRUD services above. `db_pool` is the same pool
    // the repo was constructed with (the repo's `working_days` takes it per the backbone-hr read-port
    // convention — RLS scoping is applied inside via `company_scope::fetch_all_scoped`).
    pub(crate) calendar_repository: Arc<CalendarRepository>,
    pub(crate) db_pool: sqlx::PgPool,
    // END CUSTOM
}

impl CalendarModule {
    /// Create a new module builder
    pub fn builder() -> CalendarModuleBuilder {
        CalendarModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_calendar_routes,
            create_calendar_branch_routes,
            create_calendar_department_routes,
            create_calendar_employee_routes,
            create_calendar_employee_status_routes,
            create_calendar_level_routes,
            create_calendar_position_routes,
            create_calendar_religion_routes,
        };

        Router::new()
            .merge(create_calendar_routes(self.calendar_service.clone()))
            .merge(create_calendar_branch_routes(self.calendar_branch_service.clone()))
            .merge(create_calendar_department_routes(self.calendar_department_service.clone()))
            .merge(create_calendar_employee_routes(self.calendar_employee_service.clone()))
            .merge(create_calendar_employee_status_routes(self.calendar_employee_status_service.clone()))
            .merge(create_calendar_level_routes(self.calendar_level_service.clone()))
            .merge(create_calendar_position_routes(self.calendar_position_service.clone()))
            .merge(create_calendar_religion_routes(self.calendar_religion_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for CalendarModule
pub struct CalendarModuleBuilder {
    db_pool: Option<PgPool>,
}

impl CalendarModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<CalendarModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Calendar service
        let calendar_repository = Arc::new(CalendarRepository::new(db_pool.clone()));
        let calendar_service = Arc::new(CalendarService::with_repository(calendar_repository.clone()));

        // CalendarBranch service
        let calendar_branch_repository = Arc::new(CalendarBranchRepository::new(db_pool.clone()));
        let calendar_branch_service = Arc::new(CalendarBranchService::with_repository(calendar_branch_repository.clone()));

        // CalendarDepartment service
        let calendar_department_repository = Arc::new(CalendarDepartmentRepository::new(db_pool.clone()));
        let calendar_department_service = Arc::new(CalendarDepartmentService::with_repository(calendar_department_repository.clone()));

        // CalendarEmployee service
        let calendar_employee_repository = Arc::new(CalendarEmployeeRepository::new(db_pool.clone()));
        let calendar_employee_service = Arc::new(CalendarEmployeeService::with_repository(calendar_employee_repository.clone()));

        // CalendarEmployeeStatus service
        let calendar_employee_status_repository = Arc::new(CalendarEmployeeStatusRepository::new(db_pool.clone()));
        let calendar_employee_status_service = Arc::new(CalendarEmployeeStatusService::with_repository(calendar_employee_status_repository.clone()));

        // CalendarLevel service
        let calendar_level_repository = Arc::new(CalendarLevelRepository::new(db_pool.clone()));
        let calendar_level_service = Arc::new(CalendarLevelService::with_repository(calendar_level_repository.clone()));

        // CalendarPosition service
        let calendar_position_repository = Arc::new(CalendarPositionRepository::new(db_pool.clone()));
        let calendar_position_service = Arc::new(CalendarPositionService::with_repository(calendar_position_repository.clone()));

        // CalendarReligion service
        let calendar_religion_repository = Arc::new(CalendarReligionRepository::new(db_pool.clone()));
        let calendar_religion_service = Arc::new(CalendarReligionService::with_repository(calendar_religion_repository.clone()));

        // <<< CUSTOM
        // Retain the calendar repo + pool on the module so the `CalendarQueryService` impl can
        // delegate `working_days` (custom SQL on the repo) and supply the pool the repo method takes.
        // END CUSTOM

        Ok(CalendarModule {
            calendar_service,
            calendar_branch_service,
            calendar_department_service,
            calendar_employee_service,
            calendar_employee_status_service,
            calendar_level_service,
            calendar_position_service,
            calendar_religion_service,
            // <<< CUSTOM
            calendar_repository: calendar_repository.clone(),
            db_pool,
            // END CUSTOM
        })
    }
}

impl Default for CalendarModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
