//! Use case type aliases for CalendarDepartment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarDepartmentDto, UpdateCalendarDepartmentDto};
use crate::application::service::CalendarDepartmentService;
use crate::domain::entity::CalendarDepartment;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarDepartmentUseCase = CreateUseCase<CalendarDepartment, CreateCalendarDepartmentDto, CalendarDepartmentService>;
pub type UpdateCalendarDepartmentUseCase = UpdateUseCase<CalendarDepartment, UpdateCalendarDepartmentDto, CalendarDepartmentService>;
pub type GetCalendarDepartmentUseCase    = GetUseCase<CalendarDepartment, CalendarDepartmentService>;
pub type DeleteCalendarDepartmentUseCase = DeleteUseCase<CalendarDepartment, CalendarDepartmentService>;
pub type ListCalendarDepartmentUseCase   = ListUseCase<CalendarDepartment, CalendarDepartmentService>;

// <<< CUSTOM
// END CUSTOM
