//! Use case type aliases for CalendarReligion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarReligionDto, UpdateCalendarReligionDto};
use crate::application::service::CalendarReligionService;
use crate::domain::entity::CalendarReligion;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarReligionUseCase = CreateUseCase<CalendarReligion, CreateCalendarReligionDto, CalendarReligionService>;
pub type UpdateCalendarReligionUseCase = UpdateUseCase<CalendarReligion, UpdateCalendarReligionDto, CalendarReligionService>;
pub type GetCalendarReligionUseCase    = GetUseCase<CalendarReligion, CalendarReligionService>;
pub type DeleteCalendarReligionUseCase = DeleteUseCase<CalendarReligion, CalendarReligionService>;
pub type ListCalendarReligionUseCase   = ListUseCase<CalendarReligion, CalendarReligionService>;

// <<< CUSTOM
// END CUSTOM
