//! Use case type aliases for CalendarPosition aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarPositionDto, UpdateCalendarPositionDto};
use crate::application::service::CalendarPositionService;
use crate::domain::entity::CalendarPosition;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarPositionUseCase = CreateUseCase<CalendarPosition, CreateCalendarPositionDto, CalendarPositionService>;
pub type UpdateCalendarPositionUseCase = UpdateUseCase<CalendarPosition, UpdateCalendarPositionDto, CalendarPositionService>;
pub type GetCalendarPositionUseCase    = GetUseCase<CalendarPosition, CalendarPositionService>;
pub type DeleteCalendarPositionUseCase = DeleteUseCase<CalendarPosition, CalendarPositionService>;
pub type ListCalendarPositionUseCase   = ListUseCase<CalendarPosition, CalendarPositionService>;

// <<< CUSTOM
// END CUSTOM
