//! Use case type aliases for CalendarBranch aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarBranchDto, UpdateCalendarBranchDto};
use crate::application::service::CalendarBranchService;
use crate::domain::entity::CalendarBranch;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarBranchUseCase = CreateUseCase<CalendarBranch, CreateCalendarBranchDto, CalendarBranchService>;
pub type UpdateCalendarBranchUseCase = UpdateUseCase<CalendarBranch, UpdateCalendarBranchDto, CalendarBranchService>;
pub type GetCalendarBranchUseCase    = GetUseCase<CalendarBranch, CalendarBranchService>;
pub type DeleteCalendarBranchUseCase = DeleteUseCase<CalendarBranch, CalendarBranchService>;
pub type ListCalendarBranchUseCase   = ListUseCase<CalendarBranch, CalendarBranchService>;

// <<< CUSTOM
// END CUSTOM
