//! Use case type aliases for CalendarLevel aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarLevelDto, UpdateCalendarLevelDto};
use crate::application::service::CalendarLevelService;
use crate::domain::entity::CalendarLevel;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarLevelUseCase = CreateUseCase<CalendarLevel, CreateCalendarLevelDto, CalendarLevelService>;
pub type UpdateCalendarLevelUseCase = UpdateUseCase<CalendarLevel, UpdateCalendarLevelDto, CalendarLevelService>;
pub type GetCalendarLevelUseCase    = GetUseCase<CalendarLevel, CalendarLevelService>;
pub type DeleteCalendarLevelUseCase = DeleteUseCase<CalendarLevel, CalendarLevelService>;
pub type ListCalendarLevelUseCase   = ListUseCase<CalendarLevel, CalendarLevelService>;

// <<< CUSTOM
// END CUSTOM
