//! Use case type aliases for Calendar aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarDto, UpdateCalendarDto};
use crate::application::service::CalendarService;
use crate::domain::entity::Calendar;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarUseCase = CreateUseCase<Calendar, CreateCalendarDto, CalendarService>;
pub type UpdateCalendarUseCase = UpdateUseCase<Calendar, UpdateCalendarDto, CalendarService>;
pub type GetCalendarUseCase    = GetUseCase<Calendar, CalendarService>;
pub type DeleteCalendarUseCase = DeleteUseCase<Calendar, CalendarService>;
pub type ListCalendarUseCase   = ListUseCase<Calendar, CalendarService>;

// <<< CUSTOM
// END CUSTOM
