//! Use case type aliases for CalendarEmployee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarEmployeeDto, UpdateCalendarEmployeeDto};
use crate::application::service::CalendarEmployeeService;
use crate::domain::entity::CalendarEmployee;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarEmployeeUseCase = CreateUseCase<CalendarEmployee, CreateCalendarEmployeeDto, CalendarEmployeeService>;
pub type UpdateCalendarEmployeeUseCase = UpdateUseCase<CalendarEmployee, UpdateCalendarEmployeeDto, CalendarEmployeeService>;
pub type GetCalendarEmployeeUseCase    = GetUseCase<CalendarEmployee, CalendarEmployeeService>;
pub type DeleteCalendarEmployeeUseCase = DeleteUseCase<CalendarEmployee, CalendarEmployeeService>;
pub type ListCalendarEmployeeUseCase   = ListUseCase<CalendarEmployee, CalendarEmployeeService>;

// <<< CUSTOM
// END CUSTOM
