//! Use case type aliases for CalendarEmployeeStatus aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCalendarEmployeeStatusDto, UpdateCalendarEmployeeStatusDto};
use crate::application::service::CalendarEmployeeStatusService;
use crate::domain::entity::CalendarEmployeeStatus;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCalendarEmployeeStatusUseCase = CreateUseCase<CalendarEmployeeStatus, CreateCalendarEmployeeStatusDto, CalendarEmployeeStatusService>;
pub type UpdateCalendarEmployeeStatusUseCase = UpdateUseCase<CalendarEmployeeStatus, UpdateCalendarEmployeeStatusDto, CalendarEmployeeStatusService>;
pub type GetCalendarEmployeeStatusUseCase    = GetUseCase<CalendarEmployeeStatus, CalendarEmployeeStatusService>;
pub type DeleteCalendarEmployeeStatusUseCase = DeleteUseCase<CalendarEmployeeStatus, CalendarEmployeeStatusService>;
pub type ListCalendarEmployeeStatusUseCase   = ListUseCase<CalendarEmployeeStatus, CalendarEmployeeStatusService>;

// <<< CUSTOM
// END CUSTOM
