//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod calendar_handler;
pub mod calendar_branch_handler;
pub mod calendar_department_handler;
pub mod calendar_employee_handler;
pub mod calendar_employee_status_handler;
pub mod calendar_level_handler;
pub mod calendar_position_handler;
pub mod calendar_religion_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use calendar_handler::{create_calendar_routes, create_calendar_read_routes, create_calendar_write_routes};
pub use calendar_branch_handler::{create_calendar_branch_routes, create_calendar_branch_read_routes, create_calendar_branch_write_routes};
pub use calendar_department_handler::{create_calendar_department_routes, create_calendar_department_read_routes, create_calendar_department_write_routes};
pub use calendar_employee_handler::{create_calendar_employee_routes, create_calendar_employee_read_routes, create_calendar_employee_write_routes};
pub use calendar_employee_status_handler::{create_calendar_employee_status_routes, create_calendar_employee_status_read_routes, create_calendar_employee_status_write_routes};
pub use calendar_level_handler::{create_calendar_level_routes, create_calendar_level_read_routes, create_calendar_level_write_routes};
pub use calendar_position_handler::{create_calendar_position_routes, create_calendar_position_read_routes, create_calendar_position_write_routes};
pub use calendar_religion_handler::{create_calendar_religion_routes, create_calendar_religion_read_routes, create_calendar_religion_write_routes};
// <<< CUSTOM
// END CUSTOM
